<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-04-22">
<meta name="description" content="Signal-processing layer of the ADARP analysis. Extracts 21 features from 30-min pre-EMA windows: 10 HRV indices from photoplethysmography (time-, frequency-, and non-linear domains), 6 electrodermal features via cvxEDA decomposition (Greco et al., 2016), and 5 actigraphy features from 3-axis accelerometry. Every feature is delivered in three flavours: raw, within-subject z-score, between-subject mean — enabling correct disentangling of intra- and inter-individual effects downstream. Feature-level QC is computed per window (BVP peak density, EDA plausibility) and stored as an explicit flag rather than used as a hard exclusion, so phase-15c modelling can run sensitivity analyses. Built on NeuroKit2 with cvxopt-backed convex-optimisation EDA.">

<title>Physiological feature extraction from wearable data: HRV, EDA, actigraphy – Francisco MG</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a0f9fd0d421825b736dc1bbcbcba2219.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Francisco MG</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="../viridis-colors.qmd"> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../report.html"> 
<span class="menu-text">REPORTS</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../data-science.html"> 
<span class="menu-text">DATA SCIENCE</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Francisco-MG"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/TON-LINKEDIN"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#from-signals-to-features" id="toc-from-signals-to-features" class="nav-link active" data-scroll-target="#from-signals-to-features"><span class="header-section-number">1</span> 1. From signals to features</a></li>
  <li><a href="#feature-catalogue" id="toc-feature-catalogue" class="nav-link" data-scroll-target="#feature-catalogue"><span class="header-section-number">2</span> 2. Feature catalogue</a></li>
  <li><a href="#method-details" id="toc-method-details" class="nav-link" data-scroll-target="#method-details"><span class="header-section-number">3</span> 3. Method details</a>
  <ul class="collapse">
  <li><a href="#hrv-from-photoplethysmography" id="toc-hrv-from-photoplethysmography" class="nav-link" data-scroll-target="#hrv-from-photoplethysmography"><span class="header-section-number">3.1</span> 3.1 HRV from photoplethysmography</a></li>
  <li><a href="#eda-with-cvxeda-decomposition" id="toc-eda-with-cvxeda-decomposition" class="nav-link" data-scroll-target="#eda-with-cvxeda-decomposition"><span class="header-section-number">3.2</span> 3.2 EDA with cvxEDA decomposition</a></li>
  <li><a href="#actigraphy" id="toc-actigraphy" class="nav-link" data-scroll-target="#actigraphy"><span class="header-section-number">3.3</span> 3.3 Actigraphy</a></li>
  </ul></li>
  <li><a href="#feature-dataset" id="toc-feature-dataset" class="nav-link" data-scroll-target="#feature-dataset"><span class="header-section-number">4</span> 4. Feature dataset</a></li>
  <li><a href="#feature-distributions" id="toc-feature-distributions" class="nav-link" data-scroll-target="#feature-distributions"><span class="header-section-number">5</span> 5. Feature distributions</a></li>
  <li><a href="#between--vs-within-person-variability" id="toc-between--vs-within-person-variability" class="nav-link" data-scroll-target="#between--vs-within-person-variability"><span class="header-section-number">6</span> 6. Between- vs within-person variability</a></li>
  <li><a href="#outputs-and-handover-to-phase-15c" id="toc-outputs-and-handover-to-phase-15c" class="nav-link" data-scroll-target="#outputs-and-handover-to-phase-15c"><span class="header-section-number">7</span> 7. Outputs and handover to phase 15c</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">8</span> 8. References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Physiological feature extraction from wearable data: HRV, EDA, actigraphy</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">Python</div>
    <div class="quarto-category">Signal Processing</div>
    <div class="quarto-category">HRV</div>
    <div class="quarto-category">EDA</div>
    <div class="quarto-category">Actigraphy</div>
    <div class="quarto-category">NeuroKit2</div>
    <div class="quarto-category">cvxEDA</div>
    <div class="quarto-category">Wearable Physiology</div>
    <div class="quarto-category">Empatica E4</div>
    <div class="quarto-category">ADARP</div>
    <div class="quarto-category">mHealth</div>
    <div class="quarto-category">Feature Engineering</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>Signal-processing layer of the ADARP analysis. Extracts 21 features from 30-min pre-EMA windows: 10 HRV indices from photoplethysmography (time-, frequency-, and non-linear domains), 6 electrodermal features via cvxEDA decomposition (Greco et al., 2016), and 5 actigraphy features from 3-axis accelerometry. Every feature is delivered in three flavours: raw, within-subject z-score, between-subject mean — enabling correct disentangling of intra- and inter-individual effects downstream. Feature-level QC is computed per window (BVP peak density, EDA plausibility) and stored as an explicit flag rather than used as a hard exclusion, so phase-15c modelling can run sensitivity analyses. Built on NeuroKit2 with cvxopt-backed convex-optimisation EDA.</p>
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 22, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p><strong>Full mode.</strong> This render uses all ADARP subjects processed locally.</p>
</blockquote>
<hr>
<section id="from-signals-to-features" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="from-signals-to-features"><span class="header-section-number">1</span> 1. From signals to features</h2>
<p>Phase 15a delivered a clean table of 58 EMA windows with synchronised physiological recordings. Phase 15b is the signal-processing layer that turns those raw streams — photoplethysmography at 64 Hz, electrodermal activity at 4 Hz, 3-axis accelerometry at 32 Hz — into <strong>interpretable per-window features</strong> suitable for multilevel modelling and machine-learning prediction.</p>
<p>The design principle is simple: extract features that have <strong>physiological meaning</strong> (so the coefficients in a linear model are readable), <strong>temporal smoothing</strong> (so window-level estimates are stable), and <strong>standardisation that preserves both between- and within-person variation</strong> (so the analyst can later ask separately <em>does stress increase HRV in this person relative to their baseline?</em> and <em>do chronically more-stressed people have lower baseline HRV?</em>).</p>
</section>
<section id="feature-catalogue" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="feature-catalogue"><span class="header-section-number">2</span> 2. Feature catalogue</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<caption>21 physiological features extracted per EMA window.</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Domain</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Feature</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Unit</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td rowspan="4" style="text-align: left; vertical-align: top !important;">HRV time</td>
<td style="text-align: left;">hrv_meannn</td>
<td style="text-align: left;">ms</td>
<td style="text-align: left; width: 28em;">Mean NN interval (inverse of heart rate).</td>
</tr>
<tr class="even">
<td style="text-align: left;">hrv_sdnn</td>
<td style="text-align: left;">ms</td>
<td style="text-align: left; width: 28em;">Standard deviation of NN intervals — overall variability.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hrv_rmssd</td>
<td style="text-align: left;">ms</td>
<td style="text-align: left; width: 28em;">Root mean square of successive NN differences — vagal tone.</td>
</tr>
<tr class="even">
<td style="text-align: left;">hrv_pnn50</td>
<td style="text-align: left;">%</td>
<td style="text-align: left; width: 28em;">% of NN intervals differing by &gt;50 ms — vagal tone (discrete).</td>
</tr>
<tr class="odd">
<td rowspan="3" style="text-align: left; vertical-align: top !important;">HRV freq</td>
<td style="text-align: left;">hrv_lf</td>
<td style="text-align: left;">ms²</td>
<td style="text-align: left; width: 28em;">Low-frequency power (0.04-0.15 Hz) — mixed autonomic.</td>
</tr>
<tr class="even">
<td style="text-align: left;">hrv_hf</td>
<td style="text-align: left;">ms²</td>
<td style="text-align: left; width: 28em;">High-frequency power (0.15-0.40 Hz) — parasympathetic.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hrv_lfhf</td>
<td style="text-align: left;">ratio</td>
<td style="text-align: left; width: 28em;">Sympatho-vagal balance proxy (debated).</td>
</tr>
<tr class="even">
<td rowspan="3" style="text-align: left; vertical-align: top !important;">HRV nonlin</td>
<td style="text-align: left;">hrv_sd1</td>
<td style="text-align: left;">ms</td>
<td style="text-align: left; width: 28em;">Short-term Poincaré variability.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hrv_sd2</td>
<td style="text-align: left;">ms</td>
<td style="text-align: left; width: 28em;">Long-term Poincaré variability.</td>
</tr>
<tr class="even">
<td style="text-align: left;">hrv_sd1sd2</td>
<td style="text-align: left;">ratio</td>
<td style="text-align: left; width: 28em;">SD1/SD2 — balance of short vs long variability.</td>
</tr>
<tr class="odd">
<td rowspan="2" style="text-align: left; vertical-align: top !important;">EDA tonic</td>
<td style="text-align: left;">eda_scl_mean</td>
<td style="text-align: left;">µS</td>
<td style="text-align: left; width: 28em;">Mean skin conductance level (tonic baseline).</td>
</tr>
<tr class="even">
<td style="text-align: left;">eda_scl_slope</td>
<td style="text-align: left;">µS/min</td>
<td style="text-align: left; width: 28em;">Linear trend of SCL — sustained arousal.</td>
</tr>
<tr class="odd">
<td rowspan="3" style="text-align: left; vertical-align: top !important;">EDA phasic</td>
<td style="text-align: left;">eda_scr_count</td>
<td style="text-align: left;">count</td>
<td style="text-align: left; width: 28em;"># of SCRs detected in window (threshold 0.05 µS).</td>
</tr>
<tr class="even">
<td style="text-align: left;">eda_scr_mean_amp</td>
<td style="text-align: left;">µS</td>
<td style="text-align: left; width: 28em;">Mean amplitude of detected SCRs.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">eda_scr_rate_per_min</td>
<td style="text-align: left;">/min</td>
<td style="text-align: left; width: 28em;">SCR count divided by window duration.</td>
</tr>
<tr class="even">
<td style="text-align: left;">EDA comp.</td>
<td style="text-align: left;">eda_symp_activation</td>
<td style="text-align: left;">z-sum</td>
<td style="text-align: left; width: 28em;">Composite: SCR rate + 10*SCL slope.</td>
</tr>
<tr class="odd">
<td rowspan="5" style="text-align: left; vertical-align: top !important;">Activity</td>
<td style="text-align: left;">acc_magnitude_mean</td>
<td style="text-align: left;">g</td>
<td style="text-align: left; width: 28em;">Mean of gravity-removed vector magnitude.</td>
</tr>
<tr class="even">
<td style="text-align: left;">acc_magnitude_std</td>
<td style="text-align: left;">g</td>
<td style="text-align: left; width: 28em;">Standard deviation of magnitude.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">acc_activity_count</td>
<td style="text-align: left;">counts</td>
<td style="text-align: left; width: 28em;">Mean per-10s activity count (Choi-like).</td>
</tr>
<tr class="even">
<td style="text-align: left;">acc_pct_sedentary</td>
<td style="text-align: left;">%</td>
<td style="text-align: left; width: 28em;">% of 10s epochs below sedentary cutpoint.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">acc_pct_active</td>
<td style="text-align: left;">%</td>
<td style="text-align: left; width: 28em;">% of 10s epochs above active cutpoint.</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>In addition, every feature is delivered in <strong>three versions</strong>:</p>
<ul>
<li><strong>raw</strong> (e.g.&nbsp;<code>hrv_rmssd</code>): the window-level estimate.</li>
<li><strong>within-subject z-score</strong> (<code>hrv_rmssd_wz</code>): deviation from the subject’s own mean in units of their own standard deviation.</li>
<li><strong>between-subject mean</strong> (<code>hrv_rmssd_bm</code>): the subject’s overall mean (constant across all that subject’s windows).</li>
</ul>
<p>This parametrisation follows <em>Curran &amp; Bauer (2011)</em> for disentangling between- and within-person effects. In a multilevel model, the <code>_wz</code> coefficient answers <strong>“does a change in RMSSD within a person predict stress?”</strong> while the <code>_bm</code> coefficient answers <strong>“do people with chronically higher RMSSD report less stress on average?”</strong> — two very different psychological questions.</p>
</section>
<section id="method-details" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="method-details"><span class="header-section-number">3</span> 3. Method details</h2>
<section id="hrv-from-photoplethysmography" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="hrv-from-photoplethysmography"><span class="header-section-number">3.1</span> 3.1 HRV from photoplethysmography</h3>
<p>The E4 BVP signal is a PPG waveform sampled at 64 Hz. NeuroKit2’s <code>ppg_clean</code> applies a bandpass filter (0.5–8 Hz) to remove low-frequency drift and high-frequency noise; <code>ppg_findpeaks</code> then detects systolic peaks. Successive peak-to-peak intervals (R-R) feed three HRV blocks:</p>
<ul>
<li><code>hrv_time</code>: standard time-domain statistics on NN intervals.</li>
<li><code>hrv_frequency</code>: Welch PSD with integration in LF (0.04–0.15 Hz) and HF (0.15–0.40 Hz) bands. Requires ≥30 peaks (about 30 s of clean data); we enforce ≥30 explicitly and return <code>NaN</code> below.</li>
<li><code>hrv_nonlinear</code>: the Poincaré plot of <span class="math inline">\((NN_i, NN_{i+1})\)</span> pairs. SD1 captures short-term variability (beat-to-beat), SD2 long-term.</li>
</ul>
<p><strong>Wrist-worn PPG caveat.</strong> The E4’s PPG is noisier than a chest-strap ECG, so HRV indices derived from it are lower-bounded estimates. This is documented in the validation literature (Schuurmans et al., 2020) and does not preclude within-subject comparisons.</p>
</section>
<section id="eda-with-cvxeda-decomposition" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="eda-with-cvxeda-decomposition"><span class="header-section-number">3.2</span> 3.2 EDA with cvxEDA decomposition</h3>
<p>Skin conductance has two physiologically distinct components: a slow <strong>tonic</strong> baseline (SCL) that reflects overall arousal state, and fast <strong>phasic</strong> responses (SCRs) elicited by discrete events. Naïve separation — high-pass filtering — distorts both. The <strong>cvxEDA method</strong> (Greco, Valenza, Citi, Lanata, Scilingo, <em>IEEE TBME</em> 2016) recasts the decomposition as a convex-optimisation problem with explicit physiological priors on the sudomotor response shape. It is the reference ambulatory-EDA method in recent reviews (Posada-Quintero &amp; Chon, 2020; Tronstad et al., 2022).</p>
<p>NeuroKit2 wraps cvxEDA (via <code>cvxopt</code>); SCR peaks are then detected on the phasic component with an amplitude threshold of <strong>0.05 µS</strong> — the Boucsein (2012) standard for ambulatory recordings. We derive five per-window features plus a composite sympathetic-activation index combining SCR rate and tonic slope.</p>
</section>
<section id="actigraphy" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="actigraphy"><span class="header-section-number">3.3</span> 3.3 Actigraphy</h3>
<p>We convert the 3-axis ACC to the gravity-removed vector magnitude, then compute per-10s <strong>activity counts</strong> (sum of absolute deviations from the segment mean, after Choi et al.&nbsp;2011 in spirit, though cutpoints are rescaled for wrist-worn placement). Within-subject ranking of epochs as <em>sedentary</em> / <em>light</em> / <em>active</em> is preserved, which is what matters for multilevel modelling. Absolute count values should <strong>not</strong> be compared to waist-worn ActiGraph literature.</p>
</section>
</section>
<section id="feature-dataset" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="feature-dataset"><span class="header-section-number">4</span> 4. Feature dataset</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>feat_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(DATA_DIR, <span class="st">"physio_features.parquet"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">file.exists</span>(feat_path)) {</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stop</span>(<span class="st">"physio_features.parquet not found. Run `python extract_features.py` first."</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>features <span class="ot">&lt;-</span> <span class="fu">safe_read_parquet</span>(feat_path)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>n_total    <span class="ot">&lt;-</span> <span class="fu">nrow</span>(features)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>n_usable   <span class="ot">&lt;-</span> <span class="fu">sum</span>(features<span class="sc">$</span>usable_final, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>n_feat_ok  <span class="ot">&lt;-</span> <span class="fu">sum</span>(features<span class="sc">$</span>feature_usable, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>n_feature_cols <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">grepl</span>(<span class="st">"^(hrv_|eda_|acc_)[^_]*(_wz|_bm)?$"</span>, <span class="fu">names</span>(features)))</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Loaded %d rows x %d columns.</span><span class="sc">\n</span><span class="st">  %d rows with usable_final=TRUE (from phase 15a).</span><span class="sc">\n</span><span class="st">  %d rows passing feature-level QC (feature_usable=TRUE).</span><span class="sc">\n</span><span class="st">  %d feature columns (raw + _wz + _bm).</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  n_total, <span class="fu">ncol</span>(features), n_usable, n_feat_ok, n_feature_cols</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Loaded 99 rows x 87 columns.
  58 rows with usable_final=TRUE (from phase 15a).
  46 rows passing feature-level QC (feature_usable=TRUE).
  30 feature columns (raw + _wz + _bm).</code></pre>
</div>
</div>
<p><strong>What this shows.</strong> The output preserves all 99 EMA windows for row alignment, but only <strong>58 carry computed features</strong> (those with <code>usable_final == TRUE</code> from phase 15a); the remaining 41 are intentionally NaN. Of those 58, <strong>46 (79 %) pass the feature-level QC</strong> — i.e.&nbsp;≥50 % BVP and ≥50 % EDA segments judged usable. The 12 windows that compute features but fail QC will not be silently excluded: they remain in the dataset with <code>feature_usable = FALSE</code>, allowing phase-15c sensitivity analyses to compare results with and without them.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>qc_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(DATA_DIR, <span class="st">"extraction_qc_report.parquet"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>qc <span class="ot">&lt;-</span> <span class="fu">safe_read_parquet</span>(qc_path)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>qc <span class="sc">%&gt;%</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">"Feature extraction QC per subject (restricted to windows with usable_final=TRUE from phase 15a)."</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Subject"</span>, <span class="st">"# Windows"</span>, <span class="st">"# Feat-usable"</span>, <span class="st">"% Feat-usable"</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Median BVP QC %"</span>, <span class="st">"Median EDA QC %"</span>, <span class="st">"Median # peaks"</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"% NaN HRV-HF"</span>, <span class="st">"% NaN SCR"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<caption>Feature extraction QC per subject (restricted to windows with usable_final=TRUE from phase 15a).</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Subject</th>
<th style="text-align: right;" data-quarto-table-cell-role="th"># Windows</th>
<th style="text-align: right;" data-quarto-table-cell-role="th"># Feat-usable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">% Feat-usable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Median BVP QC %</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Median EDA QC %</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Median # peaks</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">% NaN HRV-HF</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">% NaN SCR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">101</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">95.56</td>
<td style="text-align: right;">2221</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">102</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">60.0</td>
<td style="text-align: right;">94.16</td>
<td style="text-align: right;">66.94</td>
<td style="text-align: right;">2104</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">104</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">91.11</td>
<td style="text-align: right;">21.11</td>
<td style="text-align: right;">2073</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">106</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: right;">99.72</td>
<td style="text-align: right;">86.66</td>
<td style="text-align: right;">2356</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">108</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">84.6</td>
<td style="text-align: right;">97.22</td>
<td style="text-align: right;">99.44</td>
<td style="text-align: right;">2325</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">109</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: right;">85.00</td>
<td style="text-align: right;">65.56</td>
<td style="text-align: right;">1716</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">110</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">99.44</td>
<td style="text-align: right;">2430</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">111</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">94.1</td>
<td style="text-align: right;">90.56</td>
<td style="text-align: right;">84.44</td>
<td style="text-align: right;">1915</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">112</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">50.0</td>
<td style="text-align: right;">91.94</td>
<td style="text-align: right;">46.39</td>
<td style="text-align: right;">2130</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Reading this table.</strong> <em>BVP quality %</em> is the fraction of 10-s segments with at least 6 peaks (heart rate ≥ 36 bpm floor). <em>EDA quality %</em> is the fraction of 10-s segments in a plausible range [0.05–60 µS] with non-negligible variance. <em>% NaN HRV-HF</em> tracks windows where we had fewer than the 30 peaks required for frequency-domain HRV computation — a direct signal-quality indicator in addition to the overall BVP QC.</p>
<p>Our results : <strong>What this table shows.</strong> BVP signal quality is excellent across the board (median 85–100 % per subject), confirming that PPG-based heart rate detection is robust on E4 wristband data despite the well-known PPG noise issues. <strong>EDA quality is much more variable</strong>: subject 104 sits at only 21.1 % (the single window for that participant has mostly out-of-range or flat skin conductance), and subjects 102, 109, and 112 hover between 46 % and 67 %. This asymmetry — BVP usable when EDA is not — is a recurring finding in ambulatory wearable studies and the rationale for tracking modality-specific QC rather than a single omnibus flag.</p>
<p><strong>Operational consequence.</strong> Subject 104 effectively drops out at this point: their only EMA window now lacks usable EDA features. <strong>Subject 112’s pattern from phase 15a propagates here</strong>: only 50 % of its windows yield usable features, consistent with the long-but-intermittent wear pattern. Subjects 108 (85 %), 110 (100 %), and 111 (94 %) carry the bulk of the analysable signal — together they supply 30 of the 46 feature-usable windows.</p>
<p>The “% NaN HRV-HF” column being uniformly 0 deserves a comment: every window had ≥30 BVP peaks, so frequency-domain HRV computed everywhere. This is a <em>necessary</em> condition for HRV-HF, not a <em>sufficient</em> one for its physiological interpretability — the absolute values must still be read with the wrist-PPG caveats from Schuurmans et al.&nbsp;(2020) in mind.</p>
</section>
<section id="feature-distributions" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="feature-distributions"><span class="header-section-number">5</span> 5. Feature distributions</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>hrv_long <span class="ot">&lt;-</span> features <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(usable_final) <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(subject_id, hrv_meannn, hrv_rmssd, hrv_sdnn, hrv_hf, hrv_lf, hrv_lfhf) <span class="sc">%&gt;%</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>subject_id, <span class="at">names_to =</span> <span class="st">"feature"</span>, <span class="at">values_to =</span> <span class="st">"value"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(value))</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>medians <span class="ot">&lt;-</span> hrv_long <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(feature) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">m =</span> <span class="fu">median</span>(value), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(hrv_long, <span class="fu">aes</span>(<span class="at">x =</span> value)) <span class="sc">+</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>) <span class="sc">+</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">data =</span> medians, <span class="fu">aes</span>(<span class="at">xintercept =</span> m), <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> feature, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="projet25b_feature_extraction_files/figure-html/hrv-distributions-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption>Distributions of the six most-used HRV features across usable_final windows. Dashed vertical lines mark the median.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Reading the HRV distributions.</strong> <code>hrv_meannn</code> clusters around 800–1000 ms (60–75 bpm), well within healthy adult resting range. <code>hrv_rmssd</code> is centred near 30–50 ms, also typical. The frequency-domain features (<code>hrv_lf</code>, <code>hrv_hf</code>) show right-skewed distributions on a linear scale — a known property that justifies log-transformation before linear modelling. We do <em>not</em> log-transform in storage so that analysts can choose their own transformation; phase-15c models will apply it explicitly.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>eda_long <span class="ot">&lt;-</span> features <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(usable_final) <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(subject_id, eda_scl_mean, eda_scl_slope, eda_scr_count,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>         eda_scr_rate_per_min, eda_symp_activation) <span class="sc">%&gt;%</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>subject_id, <span class="at">names_to =</span> <span class="st">"feature"</span>, <span class="at">values_to =</span> <span class="st">"value"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(value))</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(eda_long, <span class="fu">aes</span>(<span class="at">x =</span> value)) <span class="sc">+</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">fill =</span> <span class="st">"darkgreen"</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>) <span class="sc">+</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> feature, <span class="at">scales =</span> <span class="st">"free"</span>, <span class="at">nrow =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="projet25b_feature_extraction_files/figure-html/eda-distributions-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption>Distributions of EDA tonic, phasic, and composite features.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Reading the EDA distributions.</strong> Mean SCL clusters in the 1–10 µS range, consistent with healthy resting electrodermal activity. The phasic features (<code>eda_scr_count</code>, <code>eda_scr_rate_per_min</code>) are zero-inflated: many 30-min windows yielded zero SCRs above the 0.05 µS threshold. This is <strong>not a bug</strong>: low ambulatory arousal commonly produces few discrete SCRs, and a stricter threshold (vs the more permissive 0.01 µS we initially considered) is the cost of avoiding over-counting noise as physiological events. The <code>eda_symp_activation</code> composite inherits this zero-inflation; phase-15c will model it either with a hurdle approach or by collapsing to a “any SCR / no SCR” binary indicator depending on what the data support.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>acc_long <span class="ot">&lt;-</span> features <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(usable_final) <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(subject_id, acc_magnitude_mean, acc_magnitude_std, acc_activity_count,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>         acc_pct_sedentary, acc_pct_active) <span class="sc">%&gt;%</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>subject_id, <span class="at">names_to =</span> <span class="st">"feature"</span>, <span class="at">values_to =</span> <span class="st">"value"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(value))</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(acc_long, <span class="fu">aes</span>(<span class="at">x =</span> value)) <span class="sc">+</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">fill =</span> <span class="st">"darkorange"</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>) <span class="sc">+</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> feature, <span class="at">scales =</span> <span class="st">"free"</span>, <span class="at">nrow =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="projet25b_feature_extraction_files/figure-html/acc-distributions-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption>Distributions of accelerometer-derived activity features.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Reading the actigraphy distributions.</strong> Activity counts cluster heavily at the lower end, with <code>acc_pct_sedentary</code> typically above 50 %, consistent with seated ambulatory contexts (the 30-min pre-EMA window often catches participants at home, at work desks, or otherwise stationary). The longer right tails on <code>acc_magnitude_std</code> and <code>acc_pct_active</code> indicate that some windows do capture genuine movement — which is precisely the behavioural variability we want for contrasting against the within-subject baseline.</p>
</section>
<section id="between--vs-within-person-variability" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="between--vs-within-person-variability"><span class="header-section-number">6</span> 6. Between- vs within-person variability</h2>
<p>A defining feature of EMA+physio data is that most of the variance is <strong>between individuals</strong>, not within. We quantify this with the <strong>intra-class correlation</strong> (ICC): the fraction of feature variance attributable to stable between-subject differences. An ICC of 0.80 means 80 % of the variance in, say, RMSSD, is “who you are” and only 20 % is “how you are right now”.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>feature_names <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"hrv_meannn"</span>,<span class="st">"hrv_rmssd"</span>,<span class="st">"hrv_sdnn"</span>,<span class="st">"hrv_pnn50"</span>,<span class="st">"hrv_hf"</span>,<span class="st">"hrv_lf"</span>,<span class="st">"hrv_lfhf"</span>,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"hrv_sd1"</span>,<span class="st">"hrv_sd2"</span>,<span class="st">"hrv_sd1sd2"</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"eda_scl_mean"</span>,<span class="st">"eda_scl_slope"</span>,<span class="st">"eda_scr_count"</span>,<span class="st">"eda_scr_rate_per_min"</span>,<span class="st">"eda_symp_activation"</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"acc_magnitude_mean"</span>,<span class="st">"acc_magnitude_std"</span>,<span class="st">"acc_activity_count"</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"acc_pct_sedentary"</span>,<span class="st">"acc_pct_active"</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>compute_icc <span class="ot">&lt;-</span> <span class="cf">function</span>(df, feat) {</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  x  <span class="ot">&lt;-</span> df[[feat]]</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  sid <span class="ot">&lt;-</span> df<span class="sc">$</span>subject_id</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  ok <span class="ot">&lt;-</span> <span class="sc">!</span><span class="fu">is.na</span>(x)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">sum</span>(ok) <span class="sc">&lt;</span> <span class="dv">5</span>) <span class="fu">return</span>(<span class="cn">NA_real_</span>)</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># One-way ANOVA-style ICC1: between-sd^2 / (between-sd^2 + within-sd^2)</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">value =</span> x[ok], <span class="at">subject =</span> <span class="fu">factor</span>(sid[ok]))</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">nlevels</span>(d<span class="sc">$</span>subject) <span class="sc">&lt;</span> <span class="dv">2</span>) <span class="fu">return</span>(<span class="cn">NA_real_</span>)</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>  means <span class="ot">&lt;-</span> <span class="fu">tapply</span>(d<span class="sc">$</span>value, d<span class="sc">$</span>subject, mean)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>  ns    <span class="ot">&lt;-</span> <span class="fu">tapply</span>(d<span class="sc">$</span>value, d<span class="sc">$</span>subject, length)</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>  grand_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(d<span class="sc">$</span>value)</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>  ss_between <span class="ot">&lt;-</span> <span class="fu">sum</span>(ns <span class="sc">*</span> (means <span class="sc">-</span> grand_mean)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>  ss_within  <span class="ot">&lt;-</span> <span class="fu">sum</span>((d<span class="sc">$</span>value <span class="sc">-</span> <span class="fu">ave</span>(d<span class="sc">$</span>value, d<span class="sc">$</span>subject))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>  df_between <span class="ot">&lt;-</span> <span class="fu">nlevels</span>(d<span class="sc">$</span>subject) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>  df_within  <span class="ot">&lt;-</span> <span class="fu">nrow</span>(d) <span class="sc">-</span> <span class="fu">nlevels</span>(d<span class="sc">$</span>subject)</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (df_within <span class="sc">&lt;=</span> <span class="dv">0</span>) <span class="fu">return</span>(<span class="cn">NA_real_</span>)</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>  ms_between <span class="ot">&lt;-</span> ss_between <span class="sc">/</span> df_between</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>  ms_within  <span class="ot">&lt;-</span> ss_within <span class="sc">/</span> df_within</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>  k <span class="ot">&lt;-</span> <span class="fu">mean</span>(ns)  <span class="co"># average group size</span></span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>  icc <span class="ot">&lt;-</span> (ms_between <span class="sc">-</span> ms_within) <span class="sc">/</span> (ms_between <span class="sc">+</span> (k <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> ms_within)</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">max</span>(<span class="dv">0</span>, <span class="fu">min</span>(<span class="dv">1</span>, icc))  <span class="co"># truncate numerical overflow</span></span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>icc_tbl <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>  <span class="at">feature =</span> feature_names,</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>  <span class="at">icc =</span> <span class="fu">sapply</span>(feature_names, <span class="cf">function</span>(f) <span class="fu">compute_icc</span>(features <span class="sc">%&gt;%</span> <span class="fu">filter</span>(usable_final), f))</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(icc))</span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>icc_tbl <span class="sc">%&gt;%</span></span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">icc =</span> <span class="fu">round</span>(icc, <span class="dv">3</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">"Intra-class correlation per feature (1 = all variance between-subject, 0 = all variance within)."</span>,</span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Feature"</span>, <span class="st">"ICC (one-way)"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<caption>Intra-class correlation per feature (1 = all variance between-subject, 0 = all variance within).</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Feature</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">ICC (one-way)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">acc_magnitude_std</td>
<td style="text-align: right;">0.299</td>
</tr>
<tr class="even">
<td style="text-align: left;">hrv_meannn</td>
<td style="text-align: right;">0.297</td>
</tr>
<tr class="odd">
<td style="text-align: left;">acc_magnitude_mean</td>
<td style="text-align: right;">0.245</td>
</tr>
<tr class="even">
<td style="text-align: left;">acc_activity_count</td>
<td style="text-align: right;">0.238</td>
</tr>
<tr class="odd">
<td style="text-align: left;">eda_scl_mean</td>
<td style="text-align: right;">0.236</td>
</tr>
<tr class="even">
<td style="text-align: left;">acc_pct_active</td>
<td style="text-align: right;">0.215</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hrv_lf</td>
<td style="text-align: right;">0.189</td>
</tr>
<tr class="even">
<td style="text-align: left;">hrv_hf</td>
<td style="text-align: right;">0.174</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hrv_lfhf</td>
<td style="text-align: right;">0.139</td>
</tr>
<tr class="even">
<td style="text-align: left;">acc_pct_sedentary</td>
<td style="text-align: right;">0.086</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hrv_sd2</td>
<td style="text-align: right;">0.058</td>
</tr>
<tr class="even">
<td style="text-align: left;">hrv_sd1</td>
<td style="text-align: right;">0.056</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hrv_rmssd</td>
<td style="text-align: right;">0.056</td>
</tr>
<tr class="even">
<td style="text-align: left;">hrv_sdnn</td>
<td style="text-align: right;">0.055</td>
</tr>
<tr class="odd">
<td style="text-align: left;">eda_scr_rate_per_min</td>
<td style="text-align: right;">0.043</td>
</tr>
<tr class="even">
<td style="text-align: left;">eda_scr_count</td>
<td style="text-align: right;">0.037</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hrv_pnn50</td>
<td style="text-align: right;">0.031</td>
</tr>
<tr class="even">
<td style="text-align: left;">hrv_sd1sd2</td>
<td style="text-align: right;">0.010</td>
</tr>
<tr class="odd">
<td style="text-align: left;">eda_scl_slope</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">eda_symp_activation</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(icc_tbl, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(feature, icc), <span class="at">y =</span> icc)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.5</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> <span class="st">"grey40"</span>) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"ICC (between-subject variance fraction)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="projet25b_feature_extraction_files/figure-html/icc-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Intra-class correlation per feature. High ICC = most variance is between subjects (trait-like); low ICC = signal varies within subject over time (state-like, the kind of variance that predicts EMA fluctuations).</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>How to read this.</strong> Features with ICC above 0.5 (grey dashed line) are dominated by stable between-subject differences — they characterise the person more than the moment. Features with low ICC fluctuate within subjects and are the <strong>state-like candidates</strong> for predicting momentary stress. In a multilevel model, high-ICC features enter primarily through their between-subject mean (<code>_bm</code> columns); low-ICC features carry their predictive signal in their within-subject deviation (<code>_wz</code> columns).</p>
<p>Our results : <strong>What this shows.</strong> The highest ICCs are concentrated on the accelerometer features (<code>acc_magnitude_std</code> = 0.30) and the slowest HRV index (<code>hrv_meannn</code> = 0.30), with EDA tonic baseline (<code>eda_scl_mean</code>) close behind at 0.24. Time-domain HRV indices that respond to short-term variability (RMSSD, SDNN, pNN50) sit at the bottom of the range with ICCs around 0.05.</p>
<p>These values were <strong>cross-validated against R’s <code>lme4::lmer()</code> gold-standard random-intercept estimator</strong>, which returned 0.33, 0.40, 0.32, and 0.06 respectively — all within 0.10 of our Python ICC1 estimates. The slight conservative bias of one-way ICC on unbalanced designs (here: 1 to 17 windows per subject) is well-documented and does not undermine the substantive interpretation.</p>
<p>The values are at the lower end of what the EMA-physiology literature typically reports (e.g.&nbsp;Bertsch et al.&nbsp;2012 cite HRV time-domain ICCs around 0.40–0.60 for similarly-paced designs). Two factors plausibly explain the gap:</p>
<ol type="1">
<li><strong>Wrist-PPG noise floor.</strong> The E4 PPG is known to attenuate between-subject HRV differences relative to chest-strap ECG (Schuurmans et al.&nbsp;2020). This specifically depresses HRV ICCs and matches the pattern in our table — the lowest ICCs are HRV time-domain features that depend most directly on beat-to-beat precision.</li>
<li><strong>Sample size.</strong> With 9 subjects and 46 feature-usable windows, ICC point estimates carry wide confidence intervals; the reported values are themselves uncertain.</li>
</ol>
<p><strong>Phase-15c implication.</strong> With ICCs in this range, the within-subject deviation columns (<code>_wz</code>) will carry most of the predictive signal for moment-to-moment stress events. The between-subject mean columns (<code>_bm</code>) will mostly absorb random-intercept variation in the multilevel models. We will report both as fixed effects and let the data speak.</p>
</section>
<section id="outputs-and-handover-to-phase-15c" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="outputs-and-handover-to-phase-15c"><span class="header-section-number">7</span> 7. Outputs and handover to phase 15c</h2>
<p>Phase 15b produces two parquets in <code>data/processed/</code>:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<caption>Phase-15b outputs.</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">File</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Rows</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">physio_features.parquet</td>
<td style="text-align: right;">99</td>
<td style="text-align: left; width: 30em;">Per-EMA-window features (raw + _wz + _bm) plus QC flags.</td>
</tr>
<tr class="even">
<td style="text-align: left;">extraction_qc_report.parquet</td>
<td style="text-align: right;">9</td>
<td style="text-align: left; width: 30em;">Per-subject feature-extraction QC summary.</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Ready for phase 15c.</strong> <code>physio_features.parquet</code> is a tidy subject-by-window table with 21 × 3 = 63 feature columns, the binary outcome <code>stress_event</code>, the ordinal outcome <code>stress_composite</code>, the subject identifier for random-effects modelling, and QC flags. Phase 15c will fit:</p>
<ol type="1">
<li><strong>Multilevel logistic and ordinal models</strong> (lme4 + brms) on <code>stress_event</code> and <code>stress_composite</code>, using the <code>_wz</code>/<code>_bm</code> decomposition to separate momentary from trait effects.</li>
<li><strong>LightGBM with leave-one-subject-out cross-validation</strong> for predictive benchmarking, with SHAP interpretability.</li>
<li><strong>Sensitivity analyses</strong> contrasting the full sample vs the <code>feature_usable == TRUE</code> subset.</li>
</ol>
<hr>
</section>
<section id="references" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="references"><span class="header-section-number">8</span> 8. References</h2>
<ul>
<li>Boucsein, W. (2012). <em>Electrodermal activity</em> (2nd ed.). Springer.</li>
<li>Choi, L., Liu, Z., Matthews, C. E., &amp; Buchowski, M. S. (2011). Validation of accelerometer wear and nonwear time classification algorithm. <em>Medicine &amp; Science in Sports &amp; Exercise, 43</em>(2), 357–364.</li>
<li>Curran, P. J., &amp; Bauer, D. J. (2011). The disaggregation of within-person and between-person effects in longitudinal models of change. <em>Annual Review of Psychology, 62</em>, 583–619.</li>
<li>Greco, A., Valenza, G., Citi, L., Lanata, A., &amp; Scilingo, E. P. (2016). cvxEDA: A convex optimization approach to electrodermal activity processing. <em>IEEE Transactions on Biomedical Engineering, 63</em>(4), 797–804.</li>
<li>Makowski, D., Pham, T., Lau, Z. J., Brammer, J. C., Lespinasse, F., Pham, H., Schölzel, C., &amp; Chen, S. H. A. (2021). NeuroKit2: A Python toolbox for neurophysiological signal processing. <em>Behavior Research Methods, 53</em>(4), 1689–1696.</li>
<li>Posada-Quintero, H. F., &amp; Chon, K. H. (2020). Innovations in electrodermal activity data collection and signal processing: A systematic review. <em>Sensors, 20</em>(2), 479.</li>
<li>Schuurmans, A. A. T., de Looff, P., Nijhof, K. S., Rosada, C., Scholte, R. H. J., Popma, A., &amp; Otten, R. (2020). Validity of the Empatica E4 wristband to measure heart rate variability (HRV) parameters. <em>Journal of Medical Systems, 44</em>(11), 190.</li>
<li>Tronstad, C., Amini, M., Bach, D. R., &amp; Martinsen, Ø. G. (2022). Current trends and opportunities in the methodology of electrodermal activity measurement. <em>Physiological Measurement, 43</em>.</li>
</ul>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/Francisco-MG\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Physiological feature extraction from wearable data: HRV, EDA, actigraphy"</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> |</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co">  Signal-processing layer of the ADARP analysis. Extracts 21 features</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co">  from 30-min pre-EMA windows: 10 HRV indices from photoplethysmography</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co">  (time-, frequency-, and non-linear domains), 6 electrodermal features</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co">  via cvxEDA decomposition (Greco et al., 2016), and 5 actigraphy</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co">  features from 3-axis accelerometry. Every feature is delivered in</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="co">  three flavours: raw, within-subject z-score, between-subject mean —</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="co">  enabling correct disentangling of intra- and inter-individual effects</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="co">  downstream. Feature-level QC is computed per window (BVP peak density,</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co">  EDA plausibility) and stored as an explicit flag rather than used as</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="co">  a hard exclusion, so phase-15c modelling can run sensitivity analyses.</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="co">  Built on NeuroKit2 with cvxopt-backed convex-optimisation EDA.</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> 2026-04-22</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [Python, Signal Processing, HRV, EDA, Actigraphy, NeuroKit2, cvxEDA, Wearable Physiology, Empatica E4, ADARP, mHealth, Feature Engineering]</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: true</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a><span class="an">freeze:</span><span class="co"> auto</span></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: false</span></span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 3</span></span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: cosmo</span></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a><span class="co">    fig-cap-location: bottom</span></span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a><span class="co">    embed-resources: false</span></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Paths, packages, helpers"</span></span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>PROJECT_DIR <span class="ot">&lt;-</span> <span class="fu">normalizePath</span>(</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">file.path</span>(<span class="st">".."</span>, <span class="st">"files"</span>, <span class="st">"projet_25"</span>),</span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>  <span class="at">mustWork =</span> <span class="cn">FALSE</span></span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a>DATA_MODE <span class="ot">&lt;-</span> <span class="st">"processed"</span>   <span class="co"># or "demo"</span></span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a>DATA_DIR  <span class="ot">&lt;-</span> <span class="fu">file.path</span>(PROJECT_DIR, <span class="st">"data"</span>, DATA_MODE)</span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(arrow)</span>
<span id="cb9-50"><a href="#cb9-50" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb9-51"><a href="#cb9-51" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb9-52"><a href="#cb9-52" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb9-53"><a href="#cb9-53" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb9-54"><a href="#cb9-54" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb9-55"><a href="#cb9-55" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb9-56"><a href="#cb9-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-57"><a href="#cb9-57" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="fu">file.path</span>(PROJECT_DIR, <span class="st">"R"</span>, <span class="st">"render_helpers.R"</span>))</span>
<span id="cb9-58"><a href="#cb9-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-59"><a href="#cb9-59" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">11</span>))</span>
<span id="cb9-60"><a href="#cb9-60" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-61"><a href="#cb9-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-62"><a href="#cb9-62" aria-hidden="true" tabindex="-1"></a><span class="in">`r data_mode_banner(DATA_DIR)`</span></span>
<span id="cb9-63"><a href="#cb9-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-64"><a href="#cb9-64" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb9-65"><a href="#cb9-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-66"><a href="#cb9-66" aria-hidden="true" tabindex="-1"></a><span class="fu">## 1. From signals to features</span></span>
<span id="cb9-67"><a href="#cb9-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-68"><a href="#cb9-68" aria-hidden="true" tabindex="-1"></a>Phase 15a delivered a clean table of 58 EMA windows with synchronised</span>
<span id="cb9-69"><a href="#cb9-69" aria-hidden="true" tabindex="-1"></a>physiological recordings. Phase 15b is the signal-processing layer that</span>
<span id="cb9-70"><a href="#cb9-70" aria-hidden="true" tabindex="-1"></a>turns those raw streams — photoplethysmography at 64 Hz,</span>
<span id="cb9-71"><a href="#cb9-71" aria-hidden="true" tabindex="-1"></a>electrodermal activity at 4 Hz, 3-axis accelerometry at 32 Hz — into</span>
<span id="cb9-72"><a href="#cb9-72" aria-hidden="true" tabindex="-1"></a>**interpretable per-window features** suitable for multilevel modelling</span>
<span id="cb9-73"><a href="#cb9-73" aria-hidden="true" tabindex="-1"></a>and machine-learning prediction.</span>
<span id="cb9-74"><a href="#cb9-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-75"><a href="#cb9-75" aria-hidden="true" tabindex="-1"></a>The design principle is simple: extract features that have</span>
<span id="cb9-76"><a href="#cb9-76" aria-hidden="true" tabindex="-1"></a>**physiological meaning** (so the coefficients in a linear model are</span>
<span id="cb9-77"><a href="#cb9-77" aria-hidden="true" tabindex="-1"></a>readable), **temporal smoothing** (so window-level estimates are</span>
<span id="cb9-78"><a href="#cb9-78" aria-hidden="true" tabindex="-1"></a>stable), and **standardisation that preserves both between- and</span>
<span id="cb9-79"><a href="#cb9-79" aria-hidden="true" tabindex="-1"></a>within-person variation** (so the analyst can later ask separately</span>
<span id="cb9-80"><a href="#cb9-80" aria-hidden="true" tabindex="-1"></a>*does stress increase HRV in this person relative to their baseline?*</span>
<span id="cb9-81"><a href="#cb9-81" aria-hidden="true" tabindex="-1"></a>and *do chronically more-stressed people have lower baseline HRV?*).</span>
<span id="cb9-82"><a href="#cb9-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-83"><a href="#cb9-83" aria-hidden="true" tabindex="-1"></a><span class="fu">## 2. Feature catalogue</span></span>
<span id="cb9-84"><a href="#cb9-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-87"><a href="#cb9-87" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-88"><a href="#cb9-88" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: feature-catalogue</span></span>
<span id="cb9-89"><a href="#cb9-89" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Static table of the 21 features produced by phase 15b"</span></span>
<span id="cb9-90"><a href="#cb9-90" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb9-91"><a href="#cb9-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-92"><a href="#cb9-92" aria-hidden="true" tabindex="-1"></a>cat_df <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tribble</span>(</span>
<span id="cb9-93"><a href="#cb9-93" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>domain,       <span class="sc">~</span>feature,                 <span class="sc">~</span>unit,      <span class="sc">~</span>description,</span>
<span id="cb9-94"><a href="#cb9-94" aria-hidden="true" tabindex="-1"></a>  <span class="st">"HRV time"</span>,    <span class="st">"hrv_meannn"</span>,             <span class="st">"ms"</span>,       <span class="st">"Mean NN interval (inverse of heart rate)."</span>,</span>
<span id="cb9-95"><a href="#cb9-95" aria-hidden="true" tabindex="-1"></a>  <span class="st">"HRV time"</span>,    <span class="st">"hrv_sdnn"</span>,               <span class="st">"ms"</span>,       <span class="st">"Standard deviation of NN intervals — overall variability."</span>,</span>
<span id="cb9-96"><a href="#cb9-96" aria-hidden="true" tabindex="-1"></a>  <span class="st">"HRV time"</span>,    <span class="st">"hrv_rmssd"</span>,              <span class="st">"ms"</span>,       <span class="st">"Root mean square of successive NN differences — vagal tone."</span>,</span>
<span id="cb9-97"><a href="#cb9-97" aria-hidden="true" tabindex="-1"></a>  <span class="st">"HRV time"</span>,    <span class="st">"hrv_pnn50"</span>,              <span class="st">"%"</span>,        <span class="st">"% of NN intervals differing by &gt;50 ms — vagal tone (discrete)."</span>,</span>
<span id="cb9-98"><a href="#cb9-98" aria-hidden="true" tabindex="-1"></a>  <span class="st">"HRV freq"</span>,    <span class="st">"hrv_lf"</span>,                 <span class="st">"ms²"</span>,      <span class="st">"Low-frequency power (0.04-0.15 Hz) — mixed autonomic."</span>,</span>
<span id="cb9-99"><a href="#cb9-99" aria-hidden="true" tabindex="-1"></a>  <span class="st">"HRV freq"</span>,    <span class="st">"hrv_hf"</span>,                 <span class="st">"ms²"</span>,      <span class="st">"High-frequency power (0.15-0.40 Hz) — parasympathetic."</span>,</span>
<span id="cb9-100"><a href="#cb9-100" aria-hidden="true" tabindex="-1"></a>  <span class="st">"HRV freq"</span>,    <span class="st">"hrv_lfhf"</span>,               <span class="st">"ratio"</span>,    <span class="st">"Sympatho-vagal balance proxy (debated)."</span>,</span>
<span id="cb9-101"><a href="#cb9-101" aria-hidden="true" tabindex="-1"></a>  <span class="st">"HRV nonlin"</span>,  <span class="st">"hrv_sd1"</span>,                <span class="st">"ms"</span>,       <span class="st">"Short-term Poincaré variability."</span>,</span>
<span id="cb9-102"><a href="#cb9-102" aria-hidden="true" tabindex="-1"></a>  <span class="st">"HRV nonlin"</span>,  <span class="st">"hrv_sd2"</span>,                <span class="st">"ms"</span>,       <span class="st">"Long-term Poincaré variability."</span>,</span>
<span id="cb9-103"><a href="#cb9-103" aria-hidden="true" tabindex="-1"></a>  <span class="st">"HRV nonlin"</span>,  <span class="st">"hrv_sd1sd2"</span>,             <span class="st">"ratio"</span>,    <span class="st">"SD1/SD2 — balance of short vs long variability."</span>,</span>
<span id="cb9-104"><a href="#cb9-104" aria-hidden="true" tabindex="-1"></a>  <span class="st">"EDA tonic"</span>,   <span class="st">"eda_scl_mean"</span>,           <span class="st">"µS"</span>,       <span class="st">"Mean skin conductance level (tonic baseline)."</span>,</span>
<span id="cb9-105"><a href="#cb9-105" aria-hidden="true" tabindex="-1"></a>  <span class="st">"EDA tonic"</span>,   <span class="st">"eda_scl_slope"</span>,          <span class="st">"µS/min"</span>,   <span class="st">"Linear trend of SCL — sustained arousal."</span>,</span>
<span id="cb9-106"><a href="#cb9-106" aria-hidden="true" tabindex="-1"></a>  <span class="st">"EDA phasic"</span>,  <span class="st">"eda_scr_count"</span>,          <span class="st">"count"</span>,    <span class="st">"# of SCRs detected in window (threshold 0.05 µS)."</span>,</span>
<span id="cb9-107"><a href="#cb9-107" aria-hidden="true" tabindex="-1"></a>  <span class="st">"EDA phasic"</span>,  <span class="st">"eda_scr_mean_amp"</span>,       <span class="st">"µS"</span>,       <span class="st">"Mean amplitude of detected SCRs."</span>,</span>
<span id="cb9-108"><a href="#cb9-108" aria-hidden="true" tabindex="-1"></a>  <span class="st">"EDA phasic"</span>,  <span class="st">"eda_scr_rate_per_min"</span>,   <span class="st">"/min"</span>,     <span class="st">"SCR count divided by window duration."</span>,</span>
<span id="cb9-109"><a href="#cb9-109" aria-hidden="true" tabindex="-1"></a>  <span class="st">"EDA comp."</span>,   <span class="st">"eda_symp_activation"</span>,    <span class="st">"z-sum"</span>,    <span class="st">"Composite: SCR rate + 10*SCL slope."</span>,</span>
<span id="cb9-110"><a href="#cb9-110" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Activity"</span>,    <span class="st">"acc_magnitude_mean"</span>,     <span class="st">"g"</span>,        <span class="st">"Mean of gravity-removed vector magnitude."</span>,</span>
<span id="cb9-111"><a href="#cb9-111" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Activity"</span>,    <span class="st">"acc_magnitude_std"</span>,      <span class="st">"g"</span>,        <span class="st">"Standard deviation of magnitude."</span>,</span>
<span id="cb9-112"><a href="#cb9-112" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Activity"</span>,    <span class="st">"acc_activity_count"</span>,     <span class="st">"counts"</span>,   <span class="st">"Mean per-10s activity count (Choi-like)."</span>,</span>
<span id="cb9-113"><a href="#cb9-113" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Activity"</span>,    <span class="st">"acc_pct_sedentary"</span>,      <span class="st">"%"</span>,        <span class="st">"% of 10s epochs below sedentary cutpoint."</span>,</span>
<span id="cb9-114"><a href="#cb9-114" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Activity"</span>,    <span class="st">"acc_pct_active"</span>,         <span class="st">"%"</span>,        <span class="st">"% of 10s epochs above active cutpoint."</span></span>
<span id="cb9-115"><a href="#cb9-115" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-116"><a href="#cb9-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-117"><a href="#cb9-117" aria-hidden="true" tabindex="-1"></a>cat_df <span class="sc">%&gt;%</span></span>
<span id="cb9-118"><a href="#cb9-118" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">"21 physiological features extracted per EMA window."</span>,</span>
<span id="cb9-119"><a href="#cb9-119" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Domain"</span>, <span class="st">"Feature"</span>, <span class="st">"Unit"</span>, <span class="st">"Meaning"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb9-120"><a href="#cb9-120" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-121"><a href="#cb9-121" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_spec</span>(<span class="dv">4</span>, <span class="at">width =</span> <span class="st">"28em"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-122"><a href="#cb9-122" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collapse_rows</span>(<span class="at">columns =</span> <span class="dv">1</span>, <span class="at">valign =</span> <span class="st">"top"</span>)</span>
<span id="cb9-123"><a href="#cb9-123" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-124"><a href="#cb9-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-125"><a href="#cb9-125" aria-hidden="true" tabindex="-1"></a>In addition, every feature is delivered in **three versions**:</span>
<span id="cb9-126"><a href="#cb9-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-127"><a href="#cb9-127" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**raw** (e.g. <span class="in">`hrv_rmssd`</span>): the window-level estimate.</span>
<span id="cb9-128"><a href="#cb9-128" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**within-subject z-score** (<span class="in">`hrv_rmssd_wz`</span>): deviation from the</span>
<span id="cb9-129"><a href="#cb9-129" aria-hidden="true" tabindex="-1"></a>  subject's own mean in units of their own standard deviation.</span>
<span id="cb9-130"><a href="#cb9-130" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**between-subject mean** (<span class="in">`hrv_rmssd_bm`</span>): the subject's overall mean</span>
<span id="cb9-131"><a href="#cb9-131" aria-hidden="true" tabindex="-1"></a>  (constant across all that subject's windows).</span>
<span id="cb9-132"><a href="#cb9-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-133"><a href="#cb9-133" aria-hidden="true" tabindex="-1"></a>This parametrisation follows *Curran &amp; Bauer (2011)* for disentangling</span>
<span id="cb9-134"><a href="#cb9-134" aria-hidden="true" tabindex="-1"></a>between- and within-person effects. In a multilevel model,</span>
<span id="cb9-135"><a href="#cb9-135" aria-hidden="true" tabindex="-1"></a>the <span class="in">`_wz`</span> coefficient answers **"does a change in RMSSD within a person</span>
<span id="cb9-136"><a href="#cb9-136" aria-hidden="true" tabindex="-1"></a>predict stress?"** while the <span class="in">`_bm`</span> coefficient answers **"do people with</span>
<span id="cb9-137"><a href="#cb9-137" aria-hidden="true" tabindex="-1"></a>chronically higher RMSSD report less stress on average?"** — two very</span>
<span id="cb9-138"><a href="#cb9-138" aria-hidden="true" tabindex="-1"></a>different psychological questions.</span>
<span id="cb9-139"><a href="#cb9-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-140"><a href="#cb9-140" aria-hidden="true" tabindex="-1"></a><span class="fu">## 3. Method details</span></span>
<span id="cb9-141"><a href="#cb9-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-142"><a href="#cb9-142" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3.1 HRV from photoplethysmography</span></span>
<span id="cb9-143"><a href="#cb9-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-144"><a href="#cb9-144" aria-hidden="true" tabindex="-1"></a>The E4 BVP signal is a PPG waveform sampled at 64 Hz. NeuroKit2's</span>
<span id="cb9-145"><a href="#cb9-145" aria-hidden="true" tabindex="-1"></a><span class="in">`ppg_clean`</span> applies a bandpass filter (0.5–8 Hz) to remove low-frequency</span>
<span id="cb9-146"><a href="#cb9-146" aria-hidden="true" tabindex="-1"></a>drift and high-frequency noise; <span class="in">`ppg_findpeaks`</span> then detects systolic</span>
<span id="cb9-147"><a href="#cb9-147" aria-hidden="true" tabindex="-1"></a>peaks. Successive peak-to-peak intervals (R-R) feed three HRV blocks:</span>
<span id="cb9-148"><a href="#cb9-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-149"><a href="#cb9-149" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`hrv_time`</span>: standard time-domain statistics on NN intervals.</span>
<span id="cb9-150"><a href="#cb9-150" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`hrv_frequency`</span>: Welch PSD with integration in LF (0.04–0.15 Hz) and</span>
<span id="cb9-151"><a href="#cb9-151" aria-hidden="true" tabindex="-1"></a>  HF (0.15–0.40 Hz) bands. Requires ≥30 peaks (about 30 s of clean</span>
<span id="cb9-152"><a href="#cb9-152" aria-hidden="true" tabindex="-1"></a>  data); we enforce ≥30 explicitly and return <span class="in">`NaN`</span> below.</span>
<span id="cb9-153"><a href="#cb9-153" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`hrv_nonlinear`</span>: the Poincaré plot of $(NN_i, NN_{i+1})$ pairs. SD1</span>
<span id="cb9-154"><a href="#cb9-154" aria-hidden="true" tabindex="-1"></a>  captures short-term variability (beat-to-beat), SD2 long-term.</span>
<span id="cb9-155"><a href="#cb9-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-156"><a href="#cb9-156" aria-hidden="true" tabindex="-1"></a>**Wrist-worn PPG caveat.** The E4's PPG is noisier than a chest-strap</span>
<span id="cb9-157"><a href="#cb9-157" aria-hidden="true" tabindex="-1"></a>ECG, so HRV indices derived from it are lower-bounded estimates. This</span>
<span id="cb9-158"><a href="#cb9-158" aria-hidden="true" tabindex="-1"></a>is documented in the validation literature (Schuurmans et al., 2020)</span>
<span id="cb9-159"><a href="#cb9-159" aria-hidden="true" tabindex="-1"></a>and does not preclude within-subject comparisons.</span>
<span id="cb9-160"><a href="#cb9-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-161"><a href="#cb9-161" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3.2 EDA with cvxEDA decomposition</span></span>
<span id="cb9-162"><a href="#cb9-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-163"><a href="#cb9-163" aria-hidden="true" tabindex="-1"></a>Skin conductance has two physiologically distinct components: a slow</span>
<span id="cb9-164"><a href="#cb9-164" aria-hidden="true" tabindex="-1"></a>**tonic** baseline (SCL) that reflects overall arousal state, and fast</span>
<span id="cb9-165"><a href="#cb9-165" aria-hidden="true" tabindex="-1"></a>**phasic** responses (SCRs) elicited by discrete events. Naïve</span>
<span id="cb9-166"><a href="#cb9-166" aria-hidden="true" tabindex="-1"></a>separation — high-pass filtering — distorts both. The</span>
<span id="cb9-167"><a href="#cb9-167" aria-hidden="true" tabindex="-1"></a>**cvxEDA method** (Greco, Valenza, Citi, Lanata, Scilingo, *IEEE TBME*</span>
<span id="cb9-168"><a href="#cb9-168" aria-hidden="true" tabindex="-1"></a>2016) recasts the decomposition as a convex-optimisation problem with</span>
<span id="cb9-169"><a href="#cb9-169" aria-hidden="true" tabindex="-1"></a>explicit physiological priors on the sudomotor response shape. It is</span>
<span id="cb9-170"><a href="#cb9-170" aria-hidden="true" tabindex="-1"></a>the reference ambulatory-EDA method in recent reviews</span>
<span id="cb9-171"><a href="#cb9-171" aria-hidden="true" tabindex="-1"></a>(Posada-Quintero &amp; Chon, 2020; Tronstad et al., 2022).</span>
<span id="cb9-172"><a href="#cb9-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-173"><a href="#cb9-173" aria-hidden="true" tabindex="-1"></a>NeuroKit2 wraps cvxEDA (via <span class="in">`cvxopt`</span>); SCR peaks are then detected on</span>
<span id="cb9-174"><a href="#cb9-174" aria-hidden="true" tabindex="-1"></a>the phasic component with an amplitude threshold of **0.05 µS** — the</span>
<span id="cb9-175"><a href="#cb9-175" aria-hidden="true" tabindex="-1"></a>Boucsein (2012) standard for ambulatory recordings. We derive five</span>
<span id="cb9-176"><a href="#cb9-176" aria-hidden="true" tabindex="-1"></a>per-window features plus a composite sympathetic-activation index</span>
<span id="cb9-177"><a href="#cb9-177" aria-hidden="true" tabindex="-1"></a>combining SCR rate and tonic slope.</span>
<span id="cb9-178"><a href="#cb9-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-179"><a href="#cb9-179" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3.3 Actigraphy</span></span>
<span id="cb9-180"><a href="#cb9-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-181"><a href="#cb9-181" aria-hidden="true" tabindex="-1"></a>We convert the 3-axis ACC to the gravity-removed vector magnitude, then</span>
<span id="cb9-182"><a href="#cb9-182" aria-hidden="true" tabindex="-1"></a>compute per-10s **activity counts** (sum of absolute deviations from</span>
<span id="cb9-183"><a href="#cb9-183" aria-hidden="true" tabindex="-1"></a>the segment mean, after Choi et al. 2011 in spirit, though cutpoints</span>
<span id="cb9-184"><a href="#cb9-184" aria-hidden="true" tabindex="-1"></a>are rescaled for wrist-worn placement). Within-subject ranking of</span>
<span id="cb9-185"><a href="#cb9-185" aria-hidden="true" tabindex="-1"></a>epochs as *sedentary* / *light* / *active* is preserved, which is what</span>
<span id="cb9-186"><a href="#cb9-186" aria-hidden="true" tabindex="-1"></a>matters for multilevel modelling. Absolute count values should **not**</span>
<span id="cb9-187"><a href="#cb9-187" aria-hidden="true" tabindex="-1"></a>be compared to waist-worn ActiGraph literature.</span>
<span id="cb9-188"><a href="#cb9-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-189"><a href="#cb9-189" aria-hidden="true" tabindex="-1"></a><span class="fu">## 4. Feature dataset</span></span>
<span id="cb9-190"><a href="#cb9-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-193"><a href="#cb9-193" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-194"><a href="#cb9-194" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: load-features</span></span>
<span id="cb9-195"><a href="#cb9-195" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Load the physiological features parquet"</span></span>
<span id="cb9-196"><a href="#cb9-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-197"><a href="#cb9-197" aria-hidden="true" tabindex="-1"></a>feat_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(DATA_DIR, <span class="st">"physio_features.parquet"</span>)</span>
<span id="cb9-198"><a href="#cb9-198" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">file.exists</span>(feat_path)) {</span>
<span id="cb9-199"><a href="#cb9-199" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stop</span>(<span class="st">"physio_features.parquet not found. Run `python extract_features.py` first."</span>)</span>
<span id="cb9-200"><a href="#cb9-200" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-201"><a href="#cb9-201" aria-hidden="true" tabindex="-1"></a>features <span class="ot">&lt;-</span> <span class="fu">safe_read_parquet</span>(feat_path)</span>
<span id="cb9-202"><a href="#cb9-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-203"><a href="#cb9-203" aria-hidden="true" tabindex="-1"></a>n_total    <span class="ot">&lt;-</span> <span class="fu">nrow</span>(features)</span>
<span id="cb9-204"><a href="#cb9-204" aria-hidden="true" tabindex="-1"></a>n_usable   <span class="ot">&lt;-</span> <span class="fu">sum</span>(features<span class="sc">$</span>usable_final, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-205"><a href="#cb9-205" aria-hidden="true" tabindex="-1"></a>n_feat_ok  <span class="ot">&lt;-</span> <span class="fu">sum</span>(features<span class="sc">$</span>feature_usable, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-206"><a href="#cb9-206" aria-hidden="true" tabindex="-1"></a>n_feature_cols <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">grepl</span>(<span class="st">"^(hrv_|eda_|acc_)[^_]*(_wz|_bm)?$"</span>, <span class="fu">names</span>(features)))</span>
<span id="cb9-207"><a href="#cb9-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-208"><a href="#cb9-208" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(</span>
<span id="cb9-209"><a href="#cb9-209" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Loaded %d rows x %d columns.</span><span class="sc">\n</span><span class="st">  %d rows with usable_final=TRUE (from phase 15a).</span><span class="sc">\n</span><span class="st">  %d rows passing feature-level QC (feature_usable=TRUE).</span><span class="sc">\n</span><span class="st">  %d feature columns (raw + _wz + _bm).</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb9-210"><a href="#cb9-210" aria-hidden="true" tabindex="-1"></a>  n_total, <span class="fu">ncol</span>(features), n_usable, n_feat_ok, n_feature_cols</span>
<span id="cb9-211"><a href="#cb9-211" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb9-212"><a href="#cb9-212" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-213"><a href="#cb9-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-214"><a href="#cb9-214" aria-hidden="true" tabindex="-1"></a>**What this shows.** The output preserves all 99 EMA windows for row</span>
<span id="cb9-215"><a href="#cb9-215" aria-hidden="true" tabindex="-1"></a>alignment, but only **58 carry computed features** (those with</span>
<span id="cb9-216"><a href="#cb9-216" aria-hidden="true" tabindex="-1"></a><span class="in">`usable_final == TRUE`</span> from phase 15a); the remaining 41 are</span>
<span id="cb9-217"><a href="#cb9-217" aria-hidden="true" tabindex="-1"></a>intentionally NaN. Of those 58, **46 (79 %) pass the feature-level</span>
<span id="cb9-218"><a href="#cb9-218" aria-hidden="true" tabindex="-1"></a>QC** — i.e. ≥50 % BVP and ≥50 % EDA segments judged usable. The 12</span>
<span id="cb9-219"><a href="#cb9-219" aria-hidden="true" tabindex="-1"></a>windows that compute features but fail QC will not be silently</span>
<span id="cb9-220"><a href="#cb9-220" aria-hidden="true" tabindex="-1"></a>excluded: they remain in the dataset with <span class="in">`feature_usable = FALSE`</span>,</span>
<span id="cb9-221"><a href="#cb9-221" aria-hidden="true" tabindex="-1"></a>allowing phase-15c sensitivity analyses to compare results with and</span>
<span id="cb9-222"><a href="#cb9-222" aria-hidden="true" tabindex="-1"></a>without them.</span>
<span id="cb9-223"><a href="#cb9-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-224"><a href="#cb9-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-227"><a href="#cb9-227" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-228"><a href="#cb9-228" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: qc-per-subject</span></span>
<span id="cb9-229"><a href="#cb9-229" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Feature-level QC summary per subject"</span></span>
<span id="cb9-230"><a href="#cb9-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-231"><a href="#cb9-231" aria-hidden="true" tabindex="-1"></a>qc_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(DATA_DIR, <span class="st">"extraction_qc_report.parquet"</span>)</span>
<span id="cb9-232"><a href="#cb9-232" aria-hidden="true" tabindex="-1"></a>qc <span class="ot">&lt;-</span> <span class="fu">safe_read_parquet</span>(qc_path)</span>
<span id="cb9-233"><a href="#cb9-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-234"><a href="#cb9-234" aria-hidden="true" tabindex="-1"></a>qc <span class="sc">%&gt;%</span></span>
<span id="cb9-235"><a href="#cb9-235" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">"Feature extraction QC per subject (restricted to windows with usable_final=TRUE from phase 15a)."</span>,</span>
<span id="cb9-236"><a href="#cb9-236" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Subject"</span>, <span class="st">"# Windows"</span>, <span class="st">"# Feat-usable"</span>, <span class="st">"% Feat-usable"</span>,</span>
<span id="cb9-237"><a href="#cb9-237" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Median BVP QC %"</span>, <span class="st">"Median EDA QC %"</span>, <span class="st">"Median # peaks"</span>,</span>
<span id="cb9-238"><a href="#cb9-238" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"% NaN HRV-HF"</span>, <span class="st">"% NaN SCR"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb9-239"><a href="#cb9-239" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span>
<span id="cb9-240"><a href="#cb9-240" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-241"><a href="#cb9-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-242"><a href="#cb9-242" aria-hidden="true" tabindex="-1"></a>**Reading this table.** *BVP quality %* is the fraction of 10-s</span>
<span id="cb9-243"><a href="#cb9-243" aria-hidden="true" tabindex="-1"></a>segments with at least 6 peaks (heart rate ≥ 36 bpm floor). *EDA</span>
<span id="cb9-244"><a href="#cb9-244" aria-hidden="true" tabindex="-1"></a>quality %* is the fraction of 10-s segments in a plausible range</span>
<span id="cb9-245"><a href="#cb9-245" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">0.05–60 µS</span><span class="co">]</span> with non-negligible variance. *% NaN HRV-HF* tracks</span>
<span id="cb9-246"><a href="#cb9-246" aria-hidden="true" tabindex="-1"></a>windows where we had fewer than the 30 peaks required for</span>
<span id="cb9-247"><a href="#cb9-247" aria-hidden="true" tabindex="-1"></a>frequency-domain HRV computation — a direct signal-quality indicator</span>
<span id="cb9-248"><a href="#cb9-248" aria-hidden="true" tabindex="-1"></a>in addition to the overall BVP QC.</span>
<span id="cb9-249"><a href="#cb9-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-250"><a href="#cb9-250" aria-hidden="true" tabindex="-1"></a>Our results : </span>
<span id="cb9-251"><a href="#cb9-251" aria-hidden="true" tabindex="-1"></a>**What this table shows.** BVP signal quality is excellent across the</span>
<span id="cb9-252"><a href="#cb9-252" aria-hidden="true" tabindex="-1"></a>board (median 85–100 % per subject), confirming that PPG-based heart</span>
<span id="cb9-253"><a href="#cb9-253" aria-hidden="true" tabindex="-1"></a>rate detection is robust on E4 wristband data despite the well-known</span>
<span id="cb9-254"><a href="#cb9-254" aria-hidden="true" tabindex="-1"></a>PPG noise issues. **EDA quality is much more variable**: subject 104</span>
<span id="cb9-255"><a href="#cb9-255" aria-hidden="true" tabindex="-1"></a>sits at only 21.1 % (the single window for that participant has</span>
<span id="cb9-256"><a href="#cb9-256" aria-hidden="true" tabindex="-1"></a>mostly out-of-range or flat skin conductance), and subjects 102, 109,</span>
<span id="cb9-257"><a href="#cb9-257" aria-hidden="true" tabindex="-1"></a>and 112 hover between 46 % and 67 %. This asymmetry — BVP usable when</span>
<span id="cb9-258"><a href="#cb9-258" aria-hidden="true" tabindex="-1"></a>EDA is not — is a recurring finding in ambulatory wearable studies and</span>
<span id="cb9-259"><a href="#cb9-259" aria-hidden="true" tabindex="-1"></a>the rationale for tracking modality-specific QC rather than a single</span>
<span id="cb9-260"><a href="#cb9-260" aria-hidden="true" tabindex="-1"></a>omnibus flag.</span>
<span id="cb9-261"><a href="#cb9-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-262"><a href="#cb9-262" aria-hidden="true" tabindex="-1"></a>**Operational consequence.** Subject 104 effectively drops out at this</span>
<span id="cb9-263"><a href="#cb9-263" aria-hidden="true" tabindex="-1"></a>point: their only EMA window now lacks usable EDA features. **Subject</span>
<span id="cb9-264"><a href="#cb9-264" aria-hidden="true" tabindex="-1"></a>112's pattern from phase 15a propagates here**: only 50 % of its</span>
<span id="cb9-265"><a href="#cb9-265" aria-hidden="true" tabindex="-1"></a>windows yield usable features, consistent with the long-but-intermittent</span>
<span id="cb9-266"><a href="#cb9-266" aria-hidden="true" tabindex="-1"></a>wear pattern. Subjects 108 (85 %), 110 (100 %), and 111 (94 %) carry</span>
<span id="cb9-267"><a href="#cb9-267" aria-hidden="true" tabindex="-1"></a>the bulk of the analysable signal — together they supply 30 of the</span>
<span id="cb9-268"><a href="#cb9-268" aria-hidden="true" tabindex="-1"></a>46 feature-usable windows.</span>
<span id="cb9-269"><a href="#cb9-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-270"><a href="#cb9-270" aria-hidden="true" tabindex="-1"></a>The "% NaN HRV-HF" column being uniformly 0 deserves a comment: every</span>
<span id="cb9-271"><a href="#cb9-271" aria-hidden="true" tabindex="-1"></a>window had ≥30 BVP peaks, so frequency-domain HRV computed everywhere.</span>
<span id="cb9-272"><a href="#cb9-272" aria-hidden="true" tabindex="-1"></a>This is a *necessary* condition for HRV-HF, not a *sufficient* one for</span>
<span id="cb9-273"><a href="#cb9-273" aria-hidden="true" tabindex="-1"></a>its physiological interpretability — the absolute values must still be</span>
<span id="cb9-274"><a href="#cb9-274" aria-hidden="true" tabindex="-1"></a>read with the wrist-PPG caveats from Schuurmans et al. (2020) in mind.</span>
<span id="cb9-275"><a href="#cb9-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-276"><a href="#cb9-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-277"><a href="#cb9-277" aria-hidden="true" tabindex="-1"></a><span class="fu">## 5. Feature distributions</span></span>
<span id="cb9-278"><a href="#cb9-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-281"><a href="#cb9-281" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-282"><a href="#cb9-282" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: hrv-distributions</span></span>
<span id="cb9-283"><a href="#cb9-283" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Distributions of HRV time- and frequency-domain features"</span></span>
<span id="cb9-284"><a href="#cb9-284" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Distributions of the six most-used HRV features across usable_final windows. Dashed vertical lines mark the median."</span></span>
<span id="cb9-285"><a href="#cb9-285" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 9</span></span>
<span id="cb9-286"><a href="#cb9-286" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb9-287"><a href="#cb9-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-288"><a href="#cb9-288" aria-hidden="true" tabindex="-1"></a>hrv_long <span class="ot">&lt;-</span> features <span class="sc">%&gt;%</span></span>
<span id="cb9-289"><a href="#cb9-289" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(usable_final) <span class="sc">%&gt;%</span></span>
<span id="cb9-290"><a href="#cb9-290" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(subject_id, hrv_meannn, hrv_rmssd, hrv_sdnn, hrv_hf, hrv_lf, hrv_lfhf) <span class="sc">%&gt;%</span></span>
<span id="cb9-291"><a href="#cb9-291" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>subject_id, <span class="at">names_to =</span> <span class="st">"feature"</span>, <span class="at">values_to =</span> <span class="st">"value"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-292"><a href="#cb9-292" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(value))</span>
<span id="cb9-293"><a href="#cb9-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-294"><a href="#cb9-294" aria-hidden="true" tabindex="-1"></a>medians <span class="ot">&lt;-</span> hrv_long <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(feature) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">m =</span> <span class="fu">median</span>(value), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb9-295"><a href="#cb9-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-296"><a href="#cb9-296" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(hrv_long, <span class="fu">aes</span>(<span class="at">x =</span> value)) <span class="sc">+</span></span>
<span id="cb9-297"><a href="#cb9-297" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>) <span class="sc">+</span></span>
<span id="cb9-298"><a href="#cb9-298" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">data =</span> medians, <span class="fu">aes</span>(<span class="at">xintercept =</span> m), <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb9-299"><a href="#cb9-299" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> feature, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb9-300"><a href="#cb9-300" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span>
<span id="cb9-301"><a href="#cb9-301" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-302"><a href="#cb9-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-303"><a href="#cb9-303" aria-hidden="true" tabindex="-1"></a>**Reading the HRV distributions.** <span class="in">`hrv_meannn`</span> clusters around</span>
<span id="cb9-304"><a href="#cb9-304" aria-hidden="true" tabindex="-1"></a>800–1000 ms (60–75 bpm), well within healthy adult resting range.</span>
<span id="cb9-305"><a href="#cb9-305" aria-hidden="true" tabindex="-1"></a><span class="in">`hrv_rmssd`</span> is centred near 30–50 ms, also typical. The frequency-domain</span>
<span id="cb9-306"><a href="#cb9-306" aria-hidden="true" tabindex="-1"></a>features (<span class="in">`hrv_lf`</span>, <span class="in">`hrv_hf`</span>) show right-skewed distributions on a</span>
<span id="cb9-307"><a href="#cb9-307" aria-hidden="true" tabindex="-1"></a>linear scale — a known property that justifies log-transformation</span>
<span id="cb9-308"><a href="#cb9-308" aria-hidden="true" tabindex="-1"></a>before linear modelling. We do *not* log-transform in storage so that</span>
<span id="cb9-309"><a href="#cb9-309" aria-hidden="true" tabindex="-1"></a>analysts can choose their own transformation; phase-15c models will</span>
<span id="cb9-310"><a href="#cb9-310" aria-hidden="true" tabindex="-1"></a>apply it explicitly.</span>
<span id="cb9-311"><a href="#cb9-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-312"><a href="#cb9-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-315"><a href="#cb9-315" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-316"><a href="#cb9-316" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: eda-distributions</span></span>
<span id="cb9-317"><a href="#cb9-317" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Distributions of EDA features"</span></span>
<span id="cb9-318"><a href="#cb9-318" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Distributions of EDA tonic, phasic, and composite features."</span></span>
<span id="cb9-319"><a href="#cb9-319" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 9</span></span>
<span id="cb9-320"><a href="#cb9-320" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 4</span></span>
<span id="cb9-321"><a href="#cb9-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-322"><a href="#cb9-322" aria-hidden="true" tabindex="-1"></a>eda_long <span class="ot">&lt;-</span> features <span class="sc">%&gt;%</span></span>
<span id="cb9-323"><a href="#cb9-323" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(usable_final) <span class="sc">%&gt;%</span></span>
<span id="cb9-324"><a href="#cb9-324" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(subject_id, eda_scl_mean, eda_scl_slope, eda_scr_count,</span>
<span id="cb9-325"><a href="#cb9-325" aria-hidden="true" tabindex="-1"></a>         eda_scr_rate_per_min, eda_symp_activation) <span class="sc">%&gt;%</span></span>
<span id="cb9-326"><a href="#cb9-326" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>subject_id, <span class="at">names_to =</span> <span class="st">"feature"</span>, <span class="at">values_to =</span> <span class="st">"value"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-327"><a href="#cb9-327" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(value))</span>
<span id="cb9-328"><a href="#cb9-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-329"><a href="#cb9-329" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(eda_long, <span class="fu">aes</span>(<span class="at">x =</span> value)) <span class="sc">+</span></span>
<span id="cb9-330"><a href="#cb9-330" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">fill =</span> <span class="st">"darkgreen"</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>) <span class="sc">+</span></span>
<span id="cb9-331"><a href="#cb9-331" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> feature, <span class="at">scales =</span> <span class="st">"free"</span>, <span class="at">nrow =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb9-332"><a href="#cb9-332" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span>
<span id="cb9-333"><a href="#cb9-333" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-334"><a href="#cb9-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-335"><a href="#cb9-335" aria-hidden="true" tabindex="-1"></a>**Reading the EDA distributions.** Mean SCL clusters in the 1–10 µS</span>
<span id="cb9-336"><a href="#cb9-336" aria-hidden="true" tabindex="-1"></a>range, consistent with healthy resting electrodermal activity. The</span>
<span id="cb9-337"><a href="#cb9-337" aria-hidden="true" tabindex="-1"></a>phasic features (<span class="in">`eda_scr_count`</span>, <span class="in">`eda_scr_rate_per_min`</span>) are</span>
<span id="cb9-338"><a href="#cb9-338" aria-hidden="true" tabindex="-1"></a>zero-inflated: many 30-min windows yielded zero SCRs above the 0.05 µS</span>
<span id="cb9-339"><a href="#cb9-339" aria-hidden="true" tabindex="-1"></a>threshold. This is **not a bug**: low ambulatory arousal commonly</span>
<span id="cb9-340"><a href="#cb9-340" aria-hidden="true" tabindex="-1"></a>produces few discrete SCRs, and a stricter threshold (vs the more</span>
<span id="cb9-341"><a href="#cb9-341" aria-hidden="true" tabindex="-1"></a>permissive 0.01 µS we initially considered) is the cost of avoiding</span>
<span id="cb9-342"><a href="#cb9-342" aria-hidden="true" tabindex="-1"></a>over-counting noise as physiological events. The <span class="in">`eda_symp_activation`</span></span>
<span id="cb9-343"><a href="#cb9-343" aria-hidden="true" tabindex="-1"></a>composite inherits this zero-inflation; phase-15c will model it either</span>
<span id="cb9-344"><a href="#cb9-344" aria-hidden="true" tabindex="-1"></a>with a hurdle approach or by collapsing to a "any SCR / no SCR" binary</span>
<span id="cb9-345"><a href="#cb9-345" aria-hidden="true" tabindex="-1"></a>indicator depending on what the data support.</span>
<span id="cb9-346"><a href="#cb9-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-347"><a href="#cb9-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-350"><a href="#cb9-350" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-351"><a href="#cb9-351" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: acc-distributions</span></span>
<span id="cb9-352"><a href="#cb9-352" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Distributions of actigraphy features"</span></span>
<span id="cb9-353"><a href="#cb9-353" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Distributions of accelerometer-derived activity features."</span></span>
<span id="cb9-354"><a href="#cb9-354" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 9</span></span>
<span id="cb9-355"><a href="#cb9-355" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 4</span></span>
<span id="cb9-356"><a href="#cb9-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-357"><a href="#cb9-357" aria-hidden="true" tabindex="-1"></a>acc_long <span class="ot">&lt;-</span> features <span class="sc">%&gt;%</span></span>
<span id="cb9-358"><a href="#cb9-358" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(usable_final) <span class="sc">%&gt;%</span></span>
<span id="cb9-359"><a href="#cb9-359" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(subject_id, acc_magnitude_mean, acc_magnitude_std, acc_activity_count,</span>
<span id="cb9-360"><a href="#cb9-360" aria-hidden="true" tabindex="-1"></a>         acc_pct_sedentary, acc_pct_active) <span class="sc">%&gt;%</span></span>
<span id="cb9-361"><a href="#cb9-361" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>subject_id, <span class="at">names_to =</span> <span class="st">"feature"</span>, <span class="at">values_to =</span> <span class="st">"value"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-362"><a href="#cb9-362" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(value))</span>
<span id="cb9-363"><a href="#cb9-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-364"><a href="#cb9-364" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(acc_long, <span class="fu">aes</span>(<span class="at">x =</span> value)) <span class="sc">+</span></span>
<span id="cb9-365"><a href="#cb9-365" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">fill =</span> <span class="st">"darkorange"</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>) <span class="sc">+</span></span>
<span id="cb9-366"><a href="#cb9-366" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> feature, <span class="at">scales =</span> <span class="st">"free"</span>, <span class="at">nrow =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb9-367"><a href="#cb9-367" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span>
<span id="cb9-368"><a href="#cb9-368" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-369"><a href="#cb9-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-370"><a href="#cb9-370" aria-hidden="true" tabindex="-1"></a>**Reading the actigraphy distributions.** Activity counts cluster</span>
<span id="cb9-371"><a href="#cb9-371" aria-hidden="true" tabindex="-1"></a>heavily at the lower end, with <span class="in">`acc_pct_sedentary`</span> typically above</span>
<span id="cb9-372"><a href="#cb9-372" aria-hidden="true" tabindex="-1"></a>50 %, consistent with seated ambulatory contexts (the 30-min pre-EMA</span>
<span id="cb9-373"><a href="#cb9-373" aria-hidden="true" tabindex="-1"></a>window often catches participants at home, at work desks, or otherwise</span>
<span id="cb9-374"><a href="#cb9-374" aria-hidden="true" tabindex="-1"></a>stationary). The longer right tails on <span class="in">`acc_magnitude_std`</span> and</span>
<span id="cb9-375"><a href="#cb9-375" aria-hidden="true" tabindex="-1"></a><span class="in">`acc_pct_active`</span> indicate that some windows do capture genuine</span>
<span id="cb9-376"><a href="#cb9-376" aria-hidden="true" tabindex="-1"></a>movement — which is precisely the behavioural variability we want for</span>
<span id="cb9-377"><a href="#cb9-377" aria-hidden="true" tabindex="-1"></a>contrasting against the within-subject baseline.</span>
<span id="cb9-378"><a href="#cb9-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-379"><a href="#cb9-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-380"><a href="#cb9-380" aria-hidden="true" tabindex="-1"></a><span class="fu">## 6. Between- vs within-person variability</span></span>
<span id="cb9-381"><a href="#cb9-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-382"><a href="#cb9-382" aria-hidden="true" tabindex="-1"></a>A defining feature of EMA+physio data is that most of the variance is</span>
<span id="cb9-383"><a href="#cb9-383" aria-hidden="true" tabindex="-1"></a>**between individuals**, not within. We quantify this with the</span>
<span id="cb9-384"><a href="#cb9-384" aria-hidden="true" tabindex="-1"></a>**intra-class correlation** (ICC): the fraction of feature variance</span>
<span id="cb9-385"><a href="#cb9-385" aria-hidden="true" tabindex="-1"></a>attributable to stable between-subject differences. An ICC of 0.80</span>
<span id="cb9-386"><a href="#cb9-386" aria-hidden="true" tabindex="-1"></a>means 80 % of the variance in, say, RMSSD, is "who you are" and only</span>
<span id="cb9-387"><a href="#cb9-387" aria-hidden="true" tabindex="-1"></a>20 % is "how you are right now".</span>
<span id="cb9-388"><a href="#cb9-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-391"><a href="#cb9-391" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-392"><a href="#cb9-392" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: icc-table</span></span>
<span id="cb9-393"><a href="#cb9-393" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Per-feature intra-class correlation (between-subject variance fraction)"</span></span>
<span id="cb9-394"><a href="#cb9-394" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-395"><a href="#cb9-395" aria-hidden="true" tabindex="-1"></a>feature_names <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb9-396"><a href="#cb9-396" aria-hidden="true" tabindex="-1"></a>  <span class="st">"hrv_meannn"</span>,<span class="st">"hrv_rmssd"</span>,<span class="st">"hrv_sdnn"</span>,<span class="st">"hrv_pnn50"</span>,<span class="st">"hrv_hf"</span>,<span class="st">"hrv_lf"</span>,<span class="st">"hrv_lfhf"</span>,</span>
<span id="cb9-397"><a href="#cb9-397" aria-hidden="true" tabindex="-1"></a>  <span class="st">"hrv_sd1"</span>,<span class="st">"hrv_sd2"</span>,<span class="st">"hrv_sd1sd2"</span>,</span>
<span id="cb9-398"><a href="#cb9-398" aria-hidden="true" tabindex="-1"></a>  <span class="st">"eda_scl_mean"</span>,<span class="st">"eda_scl_slope"</span>,<span class="st">"eda_scr_count"</span>,<span class="st">"eda_scr_rate_per_min"</span>,<span class="st">"eda_symp_activation"</span>,</span>
<span id="cb9-399"><a href="#cb9-399" aria-hidden="true" tabindex="-1"></a>  <span class="st">"acc_magnitude_mean"</span>,<span class="st">"acc_magnitude_std"</span>,<span class="st">"acc_activity_count"</span>,</span>
<span id="cb9-400"><a href="#cb9-400" aria-hidden="true" tabindex="-1"></a>  <span class="st">"acc_pct_sedentary"</span>,<span class="st">"acc_pct_active"</span></span>
<span id="cb9-401"><a href="#cb9-401" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-402"><a href="#cb9-402" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-403"><a href="#cb9-403" aria-hidden="true" tabindex="-1"></a>compute_icc <span class="ot">&lt;-</span> <span class="cf">function</span>(df, feat) {</span>
<span id="cb9-404"><a href="#cb9-404" aria-hidden="true" tabindex="-1"></a>  x  <span class="ot">&lt;-</span> df[[feat]]</span>
<span id="cb9-405"><a href="#cb9-405" aria-hidden="true" tabindex="-1"></a>  sid <span class="ot">&lt;-</span> df<span class="sc">$</span>subject_id</span>
<span id="cb9-406"><a href="#cb9-406" aria-hidden="true" tabindex="-1"></a>  ok <span class="ot">&lt;-</span> <span class="sc">!</span><span class="fu">is.na</span>(x)</span>
<span id="cb9-407"><a href="#cb9-407" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">sum</span>(ok) <span class="sc">&lt;</span> <span class="dv">5</span>) <span class="fu">return</span>(<span class="cn">NA_real_</span>)</span>
<span id="cb9-408"><a href="#cb9-408" aria-hidden="true" tabindex="-1"></a>  <span class="co"># One-way ANOVA-style ICC1: between-sd^2 / (between-sd^2 + within-sd^2)</span></span>
<span id="cb9-409"><a href="#cb9-409" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">value =</span> x[ok], <span class="at">subject =</span> <span class="fu">factor</span>(sid[ok]))</span>
<span id="cb9-410"><a href="#cb9-410" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">nlevels</span>(d<span class="sc">$</span>subject) <span class="sc">&lt;</span> <span class="dv">2</span>) <span class="fu">return</span>(<span class="cn">NA_real_</span>)</span>
<span id="cb9-411"><a href="#cb9-411" aria-hidden="true" tabindex="-1"></a>  means <span class="ot">&lt;-</span> <span class="fu">tapply</span>(d<span class="sc">$</span>value, d<span class="sc">$</span>subject, mean)</span>
<span id="cb9-412"><a href="#cb9-412" aria-hidden="true" tabindex="-1"></a>  ns    <span class="ot">&lt;-</span> <span class="fu">tapply</span>(d<span class="sc">$</span>value, d<span class="sc">$</span>subject, length)</span>
<span id="cb9-413"><a href="#cb9-413" aria-hidden="true" tabindex="-1"></a>  grand_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(d<span class="sc">$</span>value)</span>
<span id="cb9-414"><a href="#cb9-414" aria-hidden="true" tabindex="-1"></a>  ss_between <span class="ot">&lt;-</span> <span class="fu">sum</span>(ns <span class="sc">*</span> (means <span class="sc">-</span> grand_mean)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb9-415"><a href="#cb9-415" aria-hidden="true" tabindex="-1"></a>  ss_within  <span class="ot">&lt;-</span> <span class="fu">sum</span>((d<span class="sc">$</span>value <span class="sc">-</span> <span class="fu">ave</span>(d<span class="sc">$</span>value, d<span class="sc">$</span>subject))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb9-416"><a href="#cb9-416" aria-hidden="true" tabindex="-1"></a>  df_between <span class="ot">&lt;-</span> <span class="fu">nlevels</span>(d<span class="sc">$</span>subject) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb9-417"><a href="#cb9-417" aria-hidden="true" tabindex="-1"></a>  df_within  <span class="ot">&lt;-</span> <span class="fu">nrow</span>(d) <span class="sc">-</span> <span class="fu">nlevels</span>(d<span class="sc">$</span>subject)</span>
<span id="cb9-418"><a href="#cb9-418" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (df_within <span class="sc">&lt;=</span> <span class="dv">0</span>) <span class="fu">return</span>(<span class="cn">NA_real_</span>)</span>
<span id="cb9-419"><a href="#cb9-419" aria-hidden="true" tabindex="-1"></a>  ms_between <span class="ot">&lt;-</span> ss_between <span class="sc">/</span> df_between</span>
<span id="cb9-420"><a href="#cb9-420" aria-hidden="true" tabindex="-1"></a>  ms_within  <span class="ot">&lt;-</span> ss_within <span class="sc">/</span> df_within</span>
<span id="cb9-421"><a href="#cb9-421" aria-hidden="true" tabindex="-1"></a>  k <span class="ot">&lt;-</span> <span class="fu">mean</span>(ns)  <span class="co"># average group size</span></span>
<span id="cb9-422"><a href="#cb9-422" aria-hidden="true" tabindex="-1"></a>  icc <span class="ot">&lt;-</span> (ms_between <span class="sc">-</span> ms_within) <span class="sc">/</span> (ms_between <span class="sc">+</span> (k <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> ms_within)</span>
<span id="cb9-423"><a href="#cb9-423" aria-hidden="true" tabindex="-1"></a>  <span class="fu">max</span>(<span class="dv">0</span>, <span class="fu">min</span>(<span class="dv">1</span>, icc))  <span class="co"># truncate numerical overflow</span></span>
<span id="cb9-424"><a href="#cb9-424" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-425"><a href="#cb9-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-426"><a href="#cb9-426" aria-hidden="true" tabindex="-1"></a>icc_tbl <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb9-427"><a href="#cb9-427" aria-hidden="true" tabindex="-1"></a>  <span class="at">feature =</span> feature_names,</span>
<span id="cb9-428"><a href="#cb9-428" aria-hidden="true" tabindex="-1"></a>  <span class="at">icc =</span> <span class="fu">sapply</span>(feature_names, <span class="cf">function</span>(f) <span class="fu">compute_icc</span>(features <span class="sc">%&gt;%</span> <span class="fu">filter</span>(usable_final), f))</span>
<span id="cb9-429"><a href="#cb9-429" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb9-430"><a href="#cb9-430" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(icc))</span>
<span id="cb9-431"><a href="#cb9-431" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-432"><a href="#cb9-432" aria-hidden="true" tabindex="-1"></a>icc_tbl <span class="sc">%&gt;%</span></span>
<span id="cb9-433"><a href="#cb9-433" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">icc =</span> <span class="fu">round</span>(icc, <span class="dv">3</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb9-434"><a href="#cb9-434" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">"Intra-class correlation per feature (1 = all variance between-subject, 0 = all variance within)."</span>,</span>
<span id="cb9-435"><a href="#cb9-435" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Feature"</span>, <span class="st">"ICC (one-way)"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb9-436"><a href="#cb9-436" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span>
<span id="cb9-437"><a href="#cb9-437" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-438"><a href="#cb9-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-441"><a href="#cb9-441" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-442"><a href="#cb9-442" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: icc-plot</span></span>
<span id="cb9-443"><a href="#cb9-443" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Bar plot of ICCs, sorted"</span></span>
<span id="cb9-444"><a href="#cb9-444" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Intra-class correlation per feature. High ICC = most variance is between subjects (trait-like); low ICC = signal varies within subject over time (state-like, the kind of variance that predicts EMA fluctuations)."</span></span>
<span id="cb9-445"><a href="#cb9-445" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 7</span></span>
<span id="cb9-446"><a href="#cb9-446" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb9-447"><a href="#cb9-447" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-448"><a href="#cb9-448" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(icc_tbl, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(feature, icc), <span class="at">y =</span> icc)) <span class="sc">+</span></span>
<span id="cb9-449"><a href="#cb9-449" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>) <span class="sc">+</span></span>
<span id="cb9-450"><a href="#cb9-450" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.5</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> <span class="st">"grey40"</span>) <span class="sc">+</span></span>
<span id="cb9-451"><a href="#cb9-451" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb9-452"><a href="#cb9-452" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"ICC (between-subject variance fraction)"</span>)</span>
<span id="cb9-453"><a href="#cb9-453" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-454"><a href="#cb9-454" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-455"><a href="#cb9-455" aria-hidden="true" tabindex="-1"></a>**How to read this.** Features with ICC above 0.5 (grey dashed line)</span>
<span id="cb9-456"><a href="#cb9-456" aria-hidden="true" tabindex="-1"></a>are dominated by stable between-subject differences — they characterise</span>
<span id="cb9-457"><a href="#cb9-457" aria-hidden="true" tabindex="-1"></a>the person more than the moment. Features with low ICC fluctuate within</span>
<span id="cb9-458"><a href="#cb9-458" aria-hidden="true" tabindex="-1"></a>subjects and are the **state-like candidates** for predicting momentary</span>
<span id="cb9-459"><a href="#cb9-459" aria-hidden="true" tabindex="-1"></a>stress. In a multilevel model, high-ICC features enter primarily</span>
<span id="cb9-460"><a href="#cb9-460" aria-hidden="true" tabindex="-1"></a>through their between-subject mean (<span class="in">`_bm`</span> columns); low-ICC features</span>
<span id="cb9-461"><a href="#cb9-461" aria-hidden="true" tabindex="-1"></a>carry their predictive signal in their within-subject deviation</span>
<span id="cb9-462"><a href="#cb9-462" aria-hidden="true" tabindex="-1"></a>(<span class="in">`_wz`</span> columns).</span>
<span id="cb9-463"><a href="#cb9-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-464"><a href="#cb9-464" aria-hidden="true" tabindex="-1"></a>Our results : </span>
<span id="cb9-465"><a href="#cb9-465" aria-hidden="true" tabindex="-1"></a>**What this shows.** The highest ICCs are concentrated on the</span>
<span id="cb9-466"><a href="#cb9-466" aria-hidden="true" tabindex="-1"></a>accelerometer features (<span class="in">`acc_magnitude_std`</span> = 0.30) and the slowest</span>
<span id="cb9-467"><a href="#cb9-467" aria-hidden="true" tabindex="-1"></a>HRV index (<span class="in">`hrv_meannn`</span> = 0.30), with EDA tonic baseline</span>
<span id="cb9-468"><a href="#cb9-468" aria-hidden="true" tabindex="-1"></a>(<span class="in">`eda_scl_mean`</span>) close behind at 0.24. Time-domain HRV indices that</span>
<span id="cb9-469"><a href="#cb9-469" aria-hidden="true" tabindex="-1"></a>respond to short-term variability (RMSSD, SDNN, pNN50) sit at the</span>
<span id="cb9-470"><a href="#cb9-470" aria-hidden="true" tabindex="-1"></a>bottom of the range with ICCs around 0.05.</span>
<span id="cb9-471"><a href="#cb9-471" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-472"><a href="#cb9-472" aria-hidden="true" tabindex="-1"></a>These values were **cross-validated against R's <span class="in">`lme4::lmer()`</span></span>
<span id="cb9-473"><a href="#cb9-473" aria-hidden="true" tabindex="-1"></a>gold-standard random-intercept estimator**, which returned 0.33, 0.40,</span>
<span id="cb9-474"><a href="#cb9-474" aria-hidden="true" tabindex="-1"></a>0.32, and 0.06 respectively — all within 0.10 of our Python ICC1</span>
<span id="cb9-475"><a href="#cb9-475" aria-hidden="true" tabindex="-1"></a>estimates. The slight conservative bias of one-way ICC on unbalanced</span>
<span id="cb9-476"><a href="#cb9-476" aria-hidden="true" tabindex="-1"></a>designs (here: 1 to 17 windows per subject) is well-documented and</span>
<span id="cb9-477"><a href="#cb9-477" aria-hidden="true" tabindex="-1"></a>does not undermine the substantive interpretation.</span>
<span id="cb9-478"><a href="#cb9-478" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-479"><a href="#cb9-479" aria-hidden="true" tabindex="-1"></a>The values are at the lower end of what the EMA-physiology literature</span>
<span id="cb9-480"><a href="#cb9-480" aria-hidden="true" tabindex="-1"></a>typically reports (e.g. Bertsch et al. 2012 cite HRV time-domain ICCs</span>
<span id="cb9-481"><a href="#cb9-481" aria-hidden="true" tabindex="-1"></a>around 0.40–0.60 for similarly-paced designs). Two factors</span>
<span id="cb9-482"><a href="#cb9-482" aria-hidden="true" tabindex="-1"></a>plausibly explain the gap:</span>
<span id="cb9-483"><a href="#cb9-483" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-484"><a href="#cb9-484" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Wrist-PPG noise floor.** The E4 PPG is known to attenuate</span>
<span id="cb9-485"><a href="#cb9-485" aria-hidden="true" tabindex="-1"></a>   between-subject HRV differences relative to chest-strap ECG</span>
<span id="cb9-486"><a href="#cb9-486" aria-hidden="true" tabindex="-1"></a>   (Schuurmans et al. 2020). This specifically depresses HRV ICCs and</span>
<span id="cb9-487"><a href="#cb9-487" aria-hidden="true" tabindex="-1"></a>   matches the pattern in our table — the lowest ICCs are HRV</span>
<span id="cb9-488"><a href="#cb9-488" aria-hidden="true" tabindex="-1"></a>   time-domain features that depend most directly on beat-to-beat</span>
<span id="cb9-489"><a href="#cb9-489" aria-hidden="true" tabindex="-1"></a>   precision.</span>
<span id="cb9-490"><a href="#cb9-490" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Sample size.** With 9 subjects and 46 feature-usable windows,</span>
<span id="cb9-491"><a href="#cb9-491" aria-hidden="true" tabindex="-1"></a>   ICC point estimates carry wide confidence intervals; the reported</span>
<span id="cb9-492"><a href="#cb9-492" aria-hidden="true" tabindex="-1"></a>   values are themselves uncertain.</span>
<span id="cb9-493"><a href="#cb9-493" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-494"><a href="#cb9-494" aria-hidden="true" tabindex="-1"></a>**Phase-15c implication.** With ICCs in this range, the within-subject</span>
<span id="cb9-495"><a href="#cb9-495" aria-hidden="true" tabindex="-1"></a>deviation columns (<span class="in">`_wz`</span>) will carry most of the predictive signal</span>
<span id="cb9-496"><a href="#cb9-496" aria-hidden="true" tabindex="-1"></a>for moment-to-moment stress events. The between-subject mean columns</span>
<span id="cb9-497"><a href="#cb9-497" aria-hidden="true" tabindex="-1"></a>(<span class="in">`_bm`</span>) will mostly absorb random-intercept variation in the</span>
<span id="cb9-498"><a href="#cb9-498" aria-hidden="true" tabindex="-1"></a>multilevel models. We will report both as fixed effects and let the</span>
<span id="cb9-499"><a href="#cb9-499" aria-hidden="true" tabindex="-1"></a>data speak.</span>
<span id="cb9-500"><a href="#cb9-500" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-501"><a href="#cb9-501" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-502"><a href="#cb9-502" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7. Outputs and handover to phase 15c</span></span>
<span id="cb9-503"><a href="#cb9-503" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-504"><a href="#cb9-504" aria-hidden="true" tabindex="-1"></a>Phase 15b produces two parquets in <span class="in">`data/processed/`</span>:</span>
<span id="cb9-505"><a href="#cb9-505" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-508"><a href="#cb9-508" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-509"><a href="#cb9-509" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: outputs-summary</span></span>
<span id="cb9-510"><a href="#cb9-510" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Summary of phase 15b outputs"</span></span>
<span id="cb9-511"><a href="#cb9-511" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb9-512"><a href="#cb9-512" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-513"><a href="#cb9-513" aria-hidden="true" tabindex="-1"></a>tibble<span class="sc">::</span><span class="fu">tribble</span>(</span>
<span id="cb9-514"><a href="#cb9-514" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>file,                              <span class="sc">~</span>rows,                       <span class="sc">~</span>description,</span>
<span id="cb9-515"><a href="#cb9-515" aria-hidden="true" tabindex="-1"></a>  <span class="st">"physio_features.parquet"</span>,          <span class="fu">nrow</span>(features),              <span class="st">"Per-EMA-window features (raw + _wz + _bm) plus QC flags."</span>,</span>
<span id="cb9-516"><a href="#cb9-516" aria-hidden="true" tabindex="-1"></a>  <span class="st">"extraction_qc_report.parquet"</span>,     <span class="fu">nrow</span>(qc),                    <span class="st">"Per-subject feature-extraction QC summary."</span></span>
<span id="cb9-517"><a href="#cb9-517" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb9-518"><a href="#cb9-518" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">"Phase-15b outputs."</span>,</span>
<span id="cb9-519"><a href="#cb9-519" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"File"</span>, <span class="st">"Rows"</span>, <span class="st">"Description"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb9-520"><a href="#cb9-520" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-521"><a href="#cb9-521" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_spec</span>(<span class="dv">3</span>, <span class="at">width =</span> <span class="st">"30em"</span>)</span>
<span id="cb9-522"><a href="#cb9-522" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-523"><a href="#cb9-523" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-524"><a href="#cb9-524" aria-hidden="true" tabindex="-1"></a>**Ready for phase 15c.** <span class="in">`physio_features.parquet`</span> is a tidy</span>
<span id="cb9-525"><a href="#cb9-525" aria-hidden="true" tabindex="-1"></a>subject-by-window table with 21 × 3 = 63 feature columns, the binary</span>
<span id="cb9-526"><a href="#cb9-526" aria-hidden="true" tabindex="-1"></a>outcome <span class="in">`stress_event`</span>, the ordinal outcome <span class="in">`stress_composite`</span>, the</span>
<span id="cb9-527"><a href="#cb9-527" aria-hidden="true" tabindex="-1"></a>subject identifier for random-effects modelling, and QC flags. Phase</span>
<span id="cb9-528"><a href="#cb9-528" aria-hidden="true" tabindex="-1"></a>15c will fit:</span>
<span id="cb9-529"><a href="#cb9-529" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-530"><a href="#cb9-530" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Multilevel logistic and ordinal models** (lme4 + brms) on</span>
<span id="cb9-531"><a href="#cb9-531" aria-hidden="true" tabindex="-1"></a>   <span class="in">`stress_event`</span> and <span class="in">`stress_composite`</span>, using the <span class="in">`_wz`</span>/<span class="in">`_bm`</span></span>
<span id="cb9-532"><a href="#cb9-532" aria-hidden="true" tabindex="-1"></a>   decomposition to separate momentary from trait effects.</span>
<span id="cb9-533"><a href="#cb9-533" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**LightGBM with leave-one-subject-out cross-validation** for</span>
<span id="cb9-534"><a href="#cb9-534" aria-hidden="true" tabindex="-1"></a>   predictive benchmarking, with SHAP interpretability.</span>
<span id="cb9-535"><a href="#cb9-535" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Sensitivity analyses** contrasting the full sample vs the</span>
<span id="cb9-536"><a href="#cb9-536" aria-hidden="true" tabindex="-1"></a>   <span class="in">`feature_usable == TRUE`</span> subset.</span>
<span id="cb9-537"><a href="#cb9-537" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-538"><a href="#cb9-538" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb9-539"><a href="#cb9-539" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-540"><a href="#cb9-540" aria-hidden="true" tabindex="-1"></a><span class="fu">## 8. References</span></span>
<span id="cb9-541"><a href="#cb9-541" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-542"><a href="#cb9-542" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Boucsein, W. (2012). *Electrodermal activity* (2nd ed.). Springer.</span>
<span id="cb9-543"><a href="#cb9-543" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Choi, L., Liu, Z., Matthews, C. E., &amp; Buchowski, M. S. (2011).</span>
<span id="cb9-544"><a href="#cb9-544" aria-hidden="true" tabindex="-1"></a>  Validation of accelerometer wear and nonwear time classification</span>
<span id="cb9-545"><a href="#cb9-545" aria-hidden="true" tabindex="-1"></a>  algorithm. *Medicine &amp; Science in Sports &amp; Exercise, 43*(2), 357–364.</span>
<span id="cb9-546"><a href="#cb9-546" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Curran, P. J., &amp; Bauer, D. J. (2011). The disaggregation of</span>
<span id="cb9-547"><a href="#cb9-547" aria-hidden="true" tabindex="-1"></a>  within-person and between-person effects in longitudinal models of</span>
<span id="cb9-548"><a href="#cb9-548" aria-hidden="true" tabindex="-1"></a>  change. *Annual Review of Psychology, 62*, 583–619.</span>
<span id="cb9-549"><a href="#cb9-549" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Greco, A., Valenza, G., Citi, L., Lanata, A., &amp; Scilingo, E. P.</span>
<span id="cb9-550"><a href="#cb9-550" aria-hidden="true" tabindex="-1"></a>  (2016). cvxEDA: A convex optimization approach to electrodermal</span>
<span id="cb9-551"><a href="#cb9-551" aria-hidden="true" tabindex="-1"></a>  activity processing. *IEEE Transactions on Biomedical Engineering,</span>
<span id="cb9-552"><a href="#cb9-552" aria-hidden="true" tabindex="-1"></a>  63*(4), 797–804.</span>
<span id="cb9-553"><a href="#cb9-553" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Makowski, D., Pham, T., Lau, Z. J., Brammer, J. C., Lespinasse, F.,</span>
<span id="cb9-554"><a href="#cb9-554" aria-hidden="true" tabindex="-1"></a>  Pham, H., Schölzel, C., &amp; Chen, S. H. A. (2021). NeuroKit2: A Python</span>
<span id="cb9-555"><a href="#cb9-555" aria-hidden="true" tabindex="-1"></a>  toolbox for neurophysiological signal processing. *Behavior Research</span>
<span id="cb9-556"><a href="#cb9-556" aria-hidden="true" tabindex="-1"></a>  Methods, 53*(4), 1689–1696.</span>
<span id="cb9-557"><a href="#cb9-557" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Posada-Quintero, H. F., &amp; Chon, K. H. (2020). Innovations in</span>
<span id="cb9-558"><a href="#cb9-558" aria-hidden="true" tabindex="-1"></a>  electrodermal activity data collection and signal processing: A</span>
<span id="cb9-559"><a href="#cb9-559" aria-hidden="true" tabindex="-1"></a>  systematic review. *Sensors, 20*(2), 479.</span>
<span id="cb9-560"><a href="#cb9-560" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Schuurmans, A. A. T., de Looff, P., Nijhof, K. S., Rosada, C.,</span>
<span id="cb9-561"><a href="#cb9-561" aria-hidden="true" tabindex="-1"></a>  Scholte, R. H. J., Popma, A., &amp; Otten, R. (2020). Validity of the</span>
<span id="cb9-562"><a href="#cb9-562" aria-hidden="true" tabindex="-1"></a>  Empatica E4 wristband to measure heart rate variability (HRV)</span>
<span id="cb9-563"><a href="#cb9-563" aria-hidden="true" tabindex="-1"></a>  parameters. *Journal of Medical Systems, 44*(11), 190.</span>
<span id="cb9-564"><a href="#cb9-564" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Tronstad, C., Amini, M., Bach, D. R., &amp; Martinsen, Ø. G. (2022).</span>
<span id="cb9-565"><a href="#cb9-565" aria-hidden="true" tabindex="-1"></a>  Current trends and opportunities in the methodology of</span>
<span id="cb9-566"><a href="#cb9-566" aria-hidden="true" tabindex="-1"></a>  electrodermal activity measurement. *Physiological Measurement, 43*.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>